### ISSUE TITLE
"Video unavailable" even though it shows and plays fine on youtube

### ISSUE THREAD

**Issue by elypter** [omarroth/invidious#645] opened 2019-07-30 00:17 UTC
https://invidio.us/watch?v=1ASDg0qc3oI
https://invidio.us/watch?v=Hg1auv2HemI

**Comment by omarroth** [comment] 2019-07-30 01:08
Duplicate of #644, should be fixed with ff5d79e3ee1d295e97e589e39ca09bd0a880c99f.

**Closed** 2019-07-30 15:14 UTC
Labels: bug
