### ISSUE TITLE
Hello i am redy paid money you account please help me fix get video data ?

### ISSUE THREAD

**Issue by yaskammm** [omarroth/invidious#852] opened 2019-10-27 08:33 UTC
Hello i am redy paid money you account please help me, fix get video data ? You can help me ?
all work but video page not work :(

**Comment by yaskammm** [comment] 2019-10-27 08:43
my site adress http://seyret.biz:5757/watch?v=i7wveOu5hkQ

**Comment by omarroth** [comment] 2019-10-27 18:14
Duplicate of #811. 

If you have IPv6 available for your machine, you may try setting `force_resolve: ipv6` or `force_resolve: ipv4` in your config, like so:
```yaml
force_resolve: ipv6
```

**Closed by omarroth** 2019-10-27 18:14 UTC
Labels: bug, duplicate
