### ISSUE TITLE
«The media could not be loaded» on every invidious instance

### ISSUE THREAD

**Issue by stemy2** [omarroth/invidious#845] opened 2019-10-23 18:27 UTC
Hello,

I used Freetube player, but suddenly, it became unable tu grab any video. I tried all invidious public instances, but none of them work anymore, the videos are giving the message «The media could not be loaded, either because the server or network failed or because the format is not supported».

**Comment by Perflyst** [comment] 2019-10-23 18:29
Does it work in the browser? Can you try with "Proxy enabled" in the settings?

**Comment by stemy2** [comment] 2019-10-23 18:31
I don't think it's the problem. I never touched the proxy settings but invidious worked anyway.

**Comment by NettoHikari** [comment] 2019-10-23 21:55
I just encountered the same issue on my local instance, proxy enabled. I tried to load the video again and then it worked.

**Comment by Silent-Marco** [comment] 2019-10-24 02:28
I'm getting "Video unavailable" whenever I try to watch any video on invidious.

**Comment by PrestonN** [comment] 2019-10-24 02:44
This is a FreeTube only fix, however if you're on v0.7.1 then you can fix this by enabling "Play Videos Locally" in your settings. You won't have access to 1080p videos but it'll get you back up and running at least.

For anything else, it's likely a duplicate of #811.

**Comment by omarroth** [comment] 2019-11-07 15:41
Closing in favor of #811.

**Closed by omarroth** 2019-11-07 15:41 UTC
Labels: bug
