### ISSUE TITLE
Showing up as zero

### ISSUE THREAD

**Issue by NoVa-UX** [omarroth/invidious#1178] opened 2020-05-19 02:29 UTC
Sometimes I get that glitch or bug where it shows an EXTREMELY popular youtuber or one that you typically watch has NO subs no likes...no views no NOTHING.  It happens to me A LOT.  Could you PLEASE find a way to fix that?  An image down below will be provided.

![image](https://user-images.githubusercontent.com/58235380/82277945-b1572a80-994e-11ea-8ad4-d9e2fbcede0d.png)

**Comment by NoVa-UX** [comment] 2020-05-19 02:32
Another one
![image](https://user-images.githubusercontent.com/58235380/82278127-11e66780-994f-11ea-89f0-b0c637b550ef.png)

**Comment by Perflyst** [comment] 2020-05-25 19:12
Duplicate of https://github.com/omarroth/invidious/issues/753
And video stats are not shown due to https://github.com/omarroth/invidious/issues/1183

**Closed** 2020-05-26 18:03 UTC
