### ISSUE TITLE
Some videos stopped working

### ISSUE THREAD

**Issue by budg3** [omarroth/invidious#14] opened 2018-07-17 07:15 UTC
This video (https://invidio.us/watch?v=T9IdUPBcxmo) worked fine before but now it just gives:

> The media could not be loaded, either because the server or network failed or because the format is not supported.

Comparing the get_video_info (http://www.youtube.com/get_video_info?video_id=T9IdUPBcxmo) with a video that works seems to indicate that this video uses extra deciphering for its signature which could be causing it.

**Comment by omarroth** [comment] 2018-07-17 12:40
That's absolutely correct. YouTube provides a signature function with it's player as a form of DRM. Invidious can [usually decrypt](https://github.com/omarroth/invidious/blob/master/src/invidious/helpers.cr#L327) it, but it changes constantly. In the future it is expected to be able to automatically extract the signature, for now it's updated manually.

Just pushed a fix that should go live soon.

**Closed** 2018-07-17 17:14 UTC

**Comment by Zero3K** [comment] 2018-07-20 12:49
I have another video that isn't working:

https://invidio.us/embed/MEFQ7kNullM?autoplay=1&auto_play=true

**Comment by omarroth** [comment] 2018-07-20 14:13
The URL above appears to be working now. The issue is probably that the signature function just changed, and the site took a bit to update.

As a side, you don't need `&auto_play=true` in the URL.

**Comment by Zero3K** [comment] 2018-07-21 05:45
Now https://www.invidio.us/watch?v=gRG7NXd4CAE isn't working.

**Comment by omarroth** [comment] 2018-07-22 05:11
The original issue is updating signatures, which I would consider fixed. Please open a separate issue if the site is down, similar to #26. Thank you!
