### ISSUE TITLE
Search and login are broken in Chromium

### ISSUE THREAD

**Issue by narcolepticinsomniac** [omarroth/invidious#262] opened 2018-12-08 00:31 UTC
Chromium 70.0.3538.110

Error:

`Blocked form submission to '/search' because the form's frame is sandboxed and the 'allow-forms' permission is not set.`

Edit: 

Same error trying to log in:

`Blocked form submission to '/login?referer=%2F&type=invidious' because the form's frame is sandboxed and the 'allow-forms' permission is not set.`

**Comment by omarroth** [comment] 2018-12-08 00:37
I'm having trouble reproducing in Chromium 71.0.3578.80.

**Comment by narcolepticinsomniac** [comment] 2018-12-08 00:41
I can't repro in Canary or FF either, but It happens in the version noted above. Figured you might wanna know.

**Comment by omarroth** [comment] 2018-12-08 01:00
I expect this is a bug in Chromium. I'm struggling to find more info though. There's [this](https://meta.stackoverflow.com/questions/342122/cannot-post-question-from-google-chrome-because-the-forms-frame-is-sandboxed) question on SO, and [this](https://github.com/chromium/chromium/commit/0446dd0fb5e2afe4142b26c1d777af091055b9da) commit that is the closest I can find that might be relevant to this issue. There's also [this](https://stackoverflow.com/questions/39727314/sandbox-permission-errors-in-chrome-console-but-im-not-using-any-iframes) question on SO that contains similarly little info.

In any case, the error message seems irrelevant and doesn't indicate a bug in Invidious, since it doesn't use iframes.

If it's an issue in the current version, feel free to open a new issue, but for now I'm closing this.

**Closed by omarroth** 2018-12-08 01:00 UTC

**Comment by narcolepticinsomniac** [comment] 2018-12-08 01:09
Yeah, I was getting ready to close it anyway bc it started working all of a sudden. Heisenbug, I guess.
