### ISSUE TITLE
Change the country of the popular/trending videos?

### ISSUE THREAD

**Issue by sprite-1** [omarroth/invidious#1087] opened 2020-03-28 04:42 UTC
It would be great if there was an option to change the country where the popular and trending videos are being fetched from. Currently, I believe it is set to the United States.

I thought changing the language would affect it but even if I changed the language to, say, FR, it's still showing the same vdeos

**Comment by elypter** [comment] 2020-03-28 12:44
duplicate of  #331

you can do it already, just not in the ui.

**Comment by sprite-1** [comment] 2020-03-28 20:13
Doesn't seem to work for the Popular videos

**Comment by elypter** [comment] 2020-03-29 00:28
only trending

**Comment by omarroth** [comment] 2020-03-29 21:57
Popular videos are provided by Invidious, not YouTube, and are specific to the instance. Currently I don't think it's practical to provide country-specific videos on the popular page.

As @elypter mentioned, you can do this with Trending by adding `&region=REGION` to the URL, although unfortunately it's not available in the UI yet.

Closing in favor of #331.

**Closed by omarroth** 2020-03-29 21:57 UTC
Labels: duplicate, enhancement
