### ISSUE TITLE
Search returns empty regardless of what is inputted [Bug]

### ISSUE THREAD

**Issue by GreatestFool** [omarroth/invidious#1242] opened 2020-06-15 18:11 UTC
Regardless of what is inputted in title, nothing is shown. Not even the small message saying this document is empty.
![image](https://user-images.githubusercontent.com/3003484/84691342-434d5580-af44-11ea-99ab-cf0cbd4d7d67.png)

**Comment by ModdedGamers** [comment] 2020-06-15 18:12
YouTube has apparently just changed something, so that is probably what is going on. The change breaks the entirety of invidious

**Comment by Perflyst** [comment] 2020-06-15 18:12
Duplicate of #1241

**Closed by Perflyst** 2020-06-15 18:12 UTC
