### ISSUE TITLE
failed to expand heap by 16777216 bytes

### ISSUE THREAD

**Issue by MassSmith** [omarroth/invidious#536] opened 2019-05-19 04:37 UTC
useing sqlite3
GC warning: failed to expand heap by 16777216 bytes
GC warning: failed to expand heap by 16777216 bytes
GC warning: failed to expand heap by 16777216 bytes
GC warning: failed to expand heap by 16777216 bytes

installation failed

debian9
How to solve this problem?

**Comment by omarroth** [comment] 2019-05-19 12:58
Please provide more information.

- How are you running Invidious, how did you get to this point (`docker-compose`, `crystal build ...`)
- How much memory is available on your machine?

**Comment by omarroth** [comment] 2019-05-27 23:16
Unfortunately I'm going to close this for now since there isn't enough information to determine what the cause of the issue might be.

I suspect there is not enough memory available for the host to compile Invidious, recommended is at least 1GB. Please feel free to re-open with the above mentioned information.

**Closed by omarroth** 2019-05-27 23:16 UTC
Labels: bug
