### ISSUE TITLE
What about BitChute or Vimeo? Why only YouTube?

### ISSUE THREAD

**Issue by 8chanAnon** [omarroth/invidious#1010] opened 2020-02-01 14:43 UTC
Is there any possibility of expanding this project beyond just being a clone of Youtube? The community seems to be losing the battle against Youtube's IP locks. At least one instance has gone private while many of the others are either permanently locked out or are just broken. For a while now, only invidio.us and invidious.snopyta.org have been working with any degree of consistency. Side note: please fix the instances list to match the reality on the ground.

My wish list is for a site from which I can search for videos on multiple sites. Possible site list would include: Bitchute, Brighteon, Dailymotion, Infowars and Vimeo. Also: CNN, Fox, MSNBC, etc. How wonderful it would be to launch a search from Invidious and be able to view the videos without visiting those sites. Implementing a search engine wouldn't be necessary since Duckduckgo or Yippy or whatever could do the heavy lifting.

As for video playback, I have something to offer there. I've been working on a project that allows videos to be played on the browser from all of the above sites and many more without visiting or embedding the sites. However, for searching. I have to actually visit the sites. Yeah, I could use Duckduckgo to search manually but the process would be so much better with a front-end crafted for the purpose.

Anyway, if you guys want to think about this, please check out my app at the following locations:

https://archive.org/details/alleycat-player
https://github.com/8chanAnon

Thanks

**Comment by haizrul** [comment] 2020-02-01 16:01
Good idea. I support this.

**Comment by omarroth** [comment] 2020-02-01 16:19
Duplicate of #328.

As mentioned, I'm not opposed to adding other services, but I wouldn't expect it to happen soon because of the amount of work required. If anyone is interested in creating a PR I'd be happy to take a look.

**Closed by omarroth** 2020-02-01 16:19 UTC
Labels: duplicate, enhancement
