### ISSUE TITLE
docker-compose build Error "cannot find llzma"

### ISSUE THREAD

**Issue by ramsonline** [omarroth/invidious#961] opened 2019-12-18 18:26 UTC
Hi, i wanted to try the latest version of invidious and all i get is this error when i run the "docker-compose build" command

> Step 10/22 : RUN crystal build ./src/invidious.cr     --static --warnings all --error-on-warnings     -Dmusl     --link-flags "-lxml2 -llzma"
 ---> Running in adc8cea12d2d
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: cannot find -llzma (this usually means you need to install the development package for liblzma)
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o '/invidious/invidious' -lxml2 -llzma -rdynamic -static  /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a -lz /usr/lib/libyaml.a /usr/lib/libxml2.a /usr/lib/libsqlite3.a -lz /invidious/lib/lsquic/src/lsquic/ext/libssl.a `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` /invidious/lib/lsquic/src/lsquic/ext/liblsquic.a /invidious/lib/lsquic/src/lsquic/ext/libcrypto.a `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` /usr/lib/libpcre.a /usr/lib/libm.a /usr/lib/libgc.a /usr/lib/libpthread.a /usr/lib/crystal/core/ext/libcrystal.a /usr/lib/libevent.a /usr/lib/librt.a -L/usr/lib -L/usr/local/lib`
ERROR: Service 'invidious' failed to build: The command '/bin/sh -c crystal build ./src/invidious.cr     --static --warnings all --error-on-warnings     -Dmusl     --link-flags "-lxml2 -llzma"' returned a non-zero code: 1

I hope that someone can help me...

**Comment by omarroth** [comment] 2020-02-28 18:32
Duplicate of #872. Should be fixed with 59fcb56.

**Closed by omarroth** 2020-02-28 18:32 UTC
Labels: bug
