### ISSUE TITLE
The media could not be loaded, either because the server or network failed or because the format is not supported.

### ISSUE THREAD

**Issue by xqk94524** [omarroth/invidious#151] opened 2018-09-04 21:44 UTC
some times ia get this errror messenger

> The media could not be loaded, either because the server or network failed or because the format is not supported.

Windows 10 64-bits 1803 17134.228 
Mozilla Firefox 61.0.2 64-bits
Ublock Origin  1.16.20 (but don't report any block)

**Comment by xqk94524** [comment] 2018-09-04 21:54
I din't recognize any pattern
If I try with youtube-dl I see this
`WARNING: Falling back on generic information extractor.`
and star downloading with any problem, but in firefox I still can't watch

**Comment by omarroth** [comment] 2018-09-04 21:55
Looks like a problem with signature extraction. I'll try to take a look as soon as I have a chance.

**Comment by xqk94524** [comment] 2018-09-04 22:01
Okay, no hurry, thanks for the great work.

**Comment by xqk94524** [comment] 2018-09-04 22:04
using
`youtube-dl.exe -g`
I can get a working URL, if a put this on my browser, I get the video, if I reload the tab of invidio.us I can watch normaly

**Comment by omarroth** [comment] 2018-09-04 23:55
I was able to replicate it earlier but now I'm having trouble. Mind providing the video you're using or is it a site-wide issue? My guess now is that it's related to #150, and that the video is fine, but VideoJS doesn't think the browser supports playback.

**Comment by SmallJoker** [comment] 2018-09-07 17:34
I'm having the same error, but probably with a different cause:

URL: https://invidio.us/watch?v=kjPTQLgGpq8&listen=1
Browser: Firefox 61.0.1 on Ubuntu
Console log: (HTTP status code 403)
```
VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead video.min.js:1:30651
HTTP-Laden ist mit dem Status 403 fehlgeschlagen. Laden der Medienressource https://r4---sn-ab5szn7k.googlevideo.com/videoplayback?source=youtube&itag=251&ei=iLSSW4eDDsi7hgaO0ZqIDQ&pl=49&fvip=4&lmt=1513793921143233&expire=1536362728&dur=4554.541&ipbits=0&key=yt6&gir=yes&mime=audio%2Fwebm&initcwndbps=142500&requiressl=yes&ms=au%2Crdu&mv=m&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&mt=1536341027&ip=2604%3Aa880%3A400%3Ad1%3A%3A8a4%3Ab001&clen=75980465&c=WEB&keepalive=yes&id=o-AMV7WBjhN6eaBHZsUvzf0zsWqV0DzmBc1zeDnhjJ27MK&mn=sn-ab5szn7k%2Csn-ab5l6nzy&mm=31%2C29&signature=75B546B2F2B0D5AF21499CD1F406B5E1C525C45A23.A1495B6A18FC063900B503AABA15B9CCBC05985D1 fehlgeschlagen. watch
downloadable font: no supported format found (font-family: "VideoJS" style:normal weight:400 stretch:100 src index:1) source: (end of source list) unknown:1:357
HTTP-Laden ist mit dem Status 403 fehlgeschlagen. Laden der Medienressource https://r4---sn-ab5szn7k.googlevideo.com/videoplayback?source=youtube&itag=171&ei=iLSSW4eDDsi7hgaO0ZqIDQ&pl=49&fvip=4&lmt=1513794669043518&expire=1536362728&dur=4554.522&ipbits=0&key=yt6&gir=yes&mime=audio%2Fwebm&initcwndbps=142500&requiressl=yes&ms=au%2Crdu&mv=m&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&mt=1536341027&ip=2604%3Aa880%3A400%3Ad1%3A%3A8a4%3Ab001&clen=66762302&c=WEB&keepalive=yes&id=o-AMV7WBjhN6eaBHZsUvzf0zsWqV0DzmBc1zeDnhjJ27MK&mn=sn-ab5szn7k%2Csn-ab5l6nzy&mm=31%2C29&signature=D8D8359F67200D0C007D1ECCA41B807A06268C9F0E.D36C09154FAC5299F7D33D29F263A938076EB0EC8 fehlgeschlagen. watch
HTTP-Laden ist mit dem Status 403 fehlgeschlagen. Laden der Medienressource https://r4---sn-ab5szn7k.googlevideo.com/videoplayback?source=youtube&itag=140&ei=iLSSW4eDDsi7hgaO0ZqIDQ&pl=49&fvip=4&lmt=1536188919786583&expire=1536362728&dur=4554.570&ipbits=0&key=yt6&gir=yes&mime=audio%2Fmp4&initcwndbps=142500&requiressl=yes&ms=au%2Crdu&mv=m&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&mt=1536341027&ip=2604%3Aa880%3A400%3Ad1%3A%3A8a4%3Ab001&clen=72338207&c=WEB&keepalive=yes&id=o-AMV7WBjhN6eaBHZsUvzf0zsWqV0DzmBc1zeDnhjJ27MK&mn=sn-ab5szn7k%2Csn-ab5l6nzy&mm=31%2C29&signature=0B8BB537F64BDC0BD2F9679527CC9091A772403436.7FEAAE4E3E0B4CED0A8C3B3B66C388143E761F393 fehlgeschlagen. watch
HTTP-Laden ist mit dem Status 403 fehlgeschlagen. Laden der Medienressource https://r4---sn-ab5szn7k.googlevideo.com/videoplayback?source=youtube&itag=250&ei=iLSSW4eDDsi7hgaO0ZqIDQ&pl=49&fvip=4&lmt=1513793838307461&expire=1536362728&dur=4554.541&ipbits=0&key=yt6&gir=yes&mime=audio%2Fwebm&initcwndbps=142500&requiressl=yes&ms=au%2Crdu&mv=m&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&mt=1536341027&ip=2604%3Aa880%3A400%3Ad1%3A%3A8a4%3Ab001&clen=38894699&c=WEB&keepalive=yes&id=o-AMV7WBjhN6eaBHZsUvzf0zsWqV0DzmBc1zeDnhjJ27MK&mn=sn-ab5szn7k%2Csn-ab5l6nzy&mm=31%2C29&signature=7525D0BEDAA9929DB1253CA0E10AF0047C19C07138.4BD0DDD5CD88661E2D2DA38353603BE96DBA98AAD fehlgeschlagen. watch
HTTP-Laden ist mit dem Status 403 fehlgeschlagen. Laden der Medienressource https://r4---sn-ab5szn7k.googlevideo.com/videoplayback?source=youtube&itag=249&ei=iLSSW4eDDsi7hgaO0ZqIDQ&pl=49&fvip=4&lmt=1513793463655815&expire=1536362728&dur=4554.541&ipbits=0&key=yt6&gir=yes&mime=audio%2Fwebm&initcwndbps=142500&requiressl=yes&ms=au%2Crdu&mv=m&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&mt=1536341027&ip=2604%3Aa880%3A400%3Ad1%3A%3A8a4%3Ab001&clen=29614810&c=WEB&keepalive=yes&id=o-AMV7WBjhN6eaBHZsUvzf0zsWqV0DzmBc1zeDnhjJ27MK&mn=sn-ab5szn7k%2Csn-ab5l6nzy&mm=31%2C29&signature=FBAB53241EEA878F1C607C338B7528AB1C8C73CFC5.4853EC91E7C2C98A18AAD7A678F7998EB815B4C3A fehlgeschlagen. watch
Alle Kandidaten für die Ressource konnten nicht geladen werden. Medien-Laden pausiert. watch
VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) The media could not be loaded, either because the server or network failed or because the format is not supported. 
Object { code: 4, message: "The media could not be loaded, either because the server or network failed or because the format is not supported." }
video.min.js:1:30651
HTTP-Laden ist mit dem Status 403 fehlgeschlagen. Laden der Medienressource https://r4---sn-ab5szn7k.googlevideo.com/videoplayback?source=youtube&itag=250&ei=iLSSW4eDDsi7hgaO0ZqIDQ&pl=49&fvip=4&lmt=1513793838307461&expire=1536362728&dur=4554.541&ipbits=0&key=yt6&gir=yes&mime=audio%2Fwebm&initcwndbps=142500&requiressl=yes&ms=au%2Crdu&mv=m&sparams=clen%2Cdur%2Cei%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Ckeepalive%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&mt=1536341027&ip=2604%3Aa880%3A400%3Ad1%3A%3A8a4%3Ab001&clen=38894699&c=WEB&keepalive=yes&id=o-AMV7WBjhN6eaBHZsUvzf0zsWqV0DzmBc1zeDnhjJ27MK&mn=sn-ab5szn7k%2Csn-ab5l6nzy&mm=31%2C29&signature=7525D0BEDAA9929DB1253CA0E10AF0047C19C07138.4BD0DDD5CD88661E2D2DA38353603BE96DBA98AAD fehlgeschlagen.
```

**Comment by omarroth** [comment] 2018-09-07 17:41
Yep, related to rg3/youtube-dl#17457. YouTube is currently rolling out a new form of DRM that other projects are encountering as well.

**Comment by Zero3K** [comment] 2018-09-07 17:55
Here's another video that is giving the mentioned error:

https://www.invidio.us/watch?v=qmqtiVgtMcI

**Comment by omarroth** [comment] 2018-09-07 22:36
The two linked videos now work fine with 47e94fedc605a2b573eba66a243465aa049908ac. I would recommend opening new issues in the future for videos returning 403s as it makes it easier to mark a problem as fixed.

**Comment by alex9099** [comment] 2018-09-16 11:11
I think i'm getting a similar error, if i go to video tag and open the link on src on a different tab, after refresh invidio.us works ok for that video

**Comment by omarroth** [comment] 2018-09-17 22:20
I would try disabling Fanboy's Social Blocking and Fanboy's Annoyance List as a workaround. If that works, then we can close this in favor of #160.

**Comment by alex9099** [comment] 2018-09-18 21:12
i don't use any of those fanboy's stuff, i have privacy badger, duckduckgo privacy essentials, canvas blocker and descentraleyes .

For example this video https://invidio.us/watch?v=qEkCHfrLRkc yelds me that error on firefox. Chromium gets into infinite loading with "`GET https://r5---sn-2vgu0b5auxaxjvh-apne.googlevideo.com/videoplayback?source=youtube&ratebypass=yes&c=WEB&expire=1537326161&dur=352.386&requiressl=yes&pl=34&mime=video%2Fmp4&ip=2604%3Aa880%3A400%3Ad1%3A%3A82a%3Ae001&key=cms1&itag=22&ei=8WehW9TsHpjChgb-vqeIDA&ipbits=0&id=o-AEfGjx8rXJQaMbl7s7kkLjeJ1YigTB0tGbRTVsngElEc&sparams=dur,ei,expire,id,ip,ipbits,ipbypass,itag,lmt,mime,mip,mm,mn,ms,mv,pl,ratebypass,requiressl,source&txp=5431332&lmt=1537299991350508&signature=2C3E8FBF1527D51479D10EF5BCE91006EAA6777E.62415760F5F4883EB47B89AD0B50FA6E4708BA5B&fvip=4&redirect_counter=1&rm=sn-ab5rz7d&fexp=23755740,23763599&req_id=feca5469a59336e2&cms_redirect=yes&ipbypass=yes&mip=2001:8a0:7ff8:4300:2ac2:ddff:fe15:668b&mm=31&mn=sn-2vgu0b5auxaxjvh-apne&ms=au&mt=1537304856&mv=m 206 (Partial Content)`", and opera works fine out of the box

**Comment by omarroth** [comment] 2018-09-20 03:50
Would it be possible for you to disable all but one of your extensions, and re-enable them one-by-one?

**Comment by alex9099** [comment] 2018-09-20 07:29
I would try, but it seems that refreshing the page a few times also makes the error go away :confused:

**Comment by omarroth** [comment] 2018-09-29 15:37
Right, I added some info in #185. The issue is that currently while Invidious proxies video info, it does not proxy video files (except for DASH streams).

I'm planning on adding support for proxying all videos that Invidious serves, for now though you should be able to watch videos that are blocked in your region (but allowed in US) by setting `dash` as your `preferred quality`.

I think this is a duplicate of #92.

**Comment by alex9099** [comment] 2018-10-03 06:20
Hmm maybe they changed it,i recall seeing that video on YouTube in Portugal and having no restrictions (now on mobile i cant) :/

Anyway, on some videos i have to refresh the page a few times for the video to actually load

**Comment by T4eus** [comment] 2018-10-03 18:28
> Anyway, on some videos i have to refresh the page a few times for the video to actually load
https://github.com/omarroth/invidious/issues/161#issuecomment-423756026
https://github.com/omarroth/invidious/issues/161#issuecomment-424006846
there is a problem with the video source redirection, maybe this also occurs to you.
do you use Firefox or some related browser?

**Comment by RuthlessRuler** [comment] 2018-12-10 14:06
Though I'm Not getting any Error the video seems to be loading indefinitively. This happens with only some few videos like: https://invidio.us/watch?v=-CVhzHwNJ2s.
When I copy the source URL of the Video and open it in new tab it just returns a blank page.

**Comment by SmallJoker** [comment] 2018-12-10 19:24
@RuthlessRuler I also noticed that with many newer videos (< 2017 usually work fine).

Relevant console output (Firefox 63.0.3), translated because neither `LANG` not `LC_ALL` work on Firefox.

```
Unknown property '-moz-osx-font-smoothing'.  Declaration ignored.              ionicons.min.css:11:17818
VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead               video.min.js:1:30685
HTTP failed loading with status 403. Failed to load media resource https://r2---sn-ab5l6ndy.googlevideo.com/videoplayback?mime=video%2Fmp4&sparams=clen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&fvip=6&gir=yes&initcwndbps=237500&source=youtube&pl=48&ratebypass=yes&gcr=us&c=WEB&txp=5531432&requiressl=yes&mm=31%2C26&mn=sn-ab5l6ndy%2Csn-tt1e7nel&ipbits=0&mt=1544469259&mv=m&clen=12626622&ms=au%2Conr&expire=1544490975&ip=2604%3Aa880%3A400%3Ad1%3A%3A6b6%3Ab001&key=yt6&lmt=1540417413866531&dur=267.981&itag=18&id=o-AB62zpdyCjXn5sQNNKDindy1Ki4QDQNhHTqlPteZb3Vg&ei=f7sOXMH4MMTB8wScs43wBQ&signature=B2FB8111F1BBDD6F4B1CAE223C9AFDB06D8B79BE.C104EE5CC5FEE2C2AFB455C8454EC4A5D2386FA6 .              watch
The specified attribute "type" "video/3gpp; codecs="mp4v.20.3, mp4a.40.2"" is not supported. Failed to load media resource https://r2---sn-ab5l6ndy.googlevideo.com/videoplayback?mime=video%2F3gpp&sparams=clen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&fvip=6&gir=yes&initcwndbps=237500&source=youtube&pl=48&gcr=us&c=WEB&txp=5531432&requiressl=yes&mm=31%2C26&mn=sn-ab5l6ndy%2Csn-tt1e7nel&ipbits=0&mt=1544469259&mv=m&clen=7434835&ms=au%2Conr&expire=1544490975&ip=2604%3Aa880%3A400%3Ad1%3A%3A6b6%3Ab001&key=yt6&lmt=1540417455916375&dur=268.004&itag=36&id=o-AB62zpdyCjXn5sQNNKDindy1Ki4QDQNhHTqlPteZb3Vg&ei=f7sOXMH4MMTB8wScs43wBQ&signature=08C150230542B673A4E2B4F694283EA5278D29C9.6D2A534ED629012CEC173FA36E10E5FE3B8C11B4 .           watch
None of the media resources could be loaded. Media-loading paused.          watch
downloadable font: no supported format found (font-family: "VideoJS" style:normal weight:400 stretch:100 src index:1) source: (end of source list) unknown:1:357
```

**Comment by RuthlessRuler** [comment] 2018-12-12 18:13
Yes Many Videos just dont work. Even Some Old Videos dont Work, Its Very annoying sometimes to switch to YouTube.
Here is the whole Log Text:

VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead
HTTP load failed with status 403. Load of media resource https://r1---sn-ab5l6ndy.googlevideo.com/videoplayback?ratebypass=yes&clen=12442777&fvip=1&gcr=us&c=WEB&source=youtube&itag=18&lmt=1542342945367627&ipbits=0&gir=yes&requiressl=yes&ms=au%2Crdu&mt=1544637879&mv=m&pl=48&id=o-ALCYd5tl6g0AUFMckZ2cAMGT8XTuZguuAd5HzFsKZKBR&dur=262.640&mime=video%2Fmp4&sparams=clen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&ip=2604%3Aa880%3A400%3Ad1%3A%3A8a4%3Ab001&mm=31%2C29&mn=sn-ab5l6ndy%2Csn-ab5sznlk&ei=GE4RXIqSLsiqhwbAhoTYCQ&key=yt6&txp=5531432&initcwndbps=243750&expire=1544659576&signature=411DDC06146E629291FE97A3DB84C9F457707791.DE0D805BAE817216DA980FEDA3A36A60A6A792B2 failed. 
Specified “type” attribute of “video/3gpp; codecs="mp4v.20.3, mp4a.40.2"” is not supported. Load of media resource https://r1---sn-ab5l6ndy.googlevideo.com/videoplayback?clen=7665164&fvip=1&gcr=us&c=WEB&source=youtube&itag=36&lmt=1542343027359633&ipbits=0&gir=yes&requiressl=yes&ms=au%2Crdu&mt=1544637879&mv=m&pl=48&id=o-ALCYd5tl6g0AUFMckZ2cAMGT8XTuZguuAd5HzFsKZKBR&dur=262.664&mime=video%2F3gpp&sparams=clen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&ip=2604%3Aa880%3A400%3Ad1%3A%3A8a4%3Ab001&mm=31%2C29&mn=sn-ab5l6ndy%2Csn-ab5sznlk&ei=GE4RXIqSLsiqhwbAhoTYCQ&key=yt6&txp=5531432&initcwndbps=243750&expire=1544659576&signature=09BE639EF0A7A0E9BCBC38FCF4F2F688D1BB9EC0.1CD76F0A7EB54A621B691C32AEDA7CC9FECDA7A9 failed. 
All candidate resources failed to load. Media load paused.

**Comment by alex9099** [comment] 2019-01-12 18:31
Same with https://www.youtube.com/watch?v=UYwF-jdcVjY for example, though youtube-dl is able to download it and newpipe is also able to play it (IIRC there is no video that newpipe can't play, not sure how it works though)

`VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead video.min.js:1:30685
HTTP load failed with status 403. Load of media resource https://r4---sn-ab5l6nsk.googlevideo.com/videoplayback?txp=5531432&key=yt6&ip=2604%3Aa880%3A400%3Ad1%3A%3A6b6%3Ab001&dur=232.083&lmt=1543881029960428&id=o-AHuJl6ojxVLHderG-brdugAe-S_R2eet7WlUdu4d2PxL&itag=18&requiressl=yes&ipbits=0&mn=sn-ab5l6nsk%2Csn-vgqsrnes&mm=31%2C26&ms=au%2Conr&ei=OTE6XLKnGoL78wSJnZy4Aw&mv=m&mt=1547317447&expire=1547339161&initcwndbps=163750&gir=yes&ratebypass=yes&pl=49&source=youtube&gcr=us&c=WEB&mime=video%2Fmp4&fvip=4&sparams=clen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Cratebypass%2Crequiressl%2Csource%2Cexpire&clen=13298662&signature=B429575CEF74E1AF1641F28EA35D83CFA5F96666.734E9154DFA0403BDA6A2BACB12BB56820A3F1BE failed. watch
Specified “type” attribute of “video/3gpp; codecs="mp4v.20.3, mp4a.40.2"” is not supported. Load of media resource https://r4---sn-ab5l6nsk.googlevideo.com/videoplayback?txp=5531432&key=yt6&ip=2604%3Aa880%3A400%3Ad1%3A%3A6b6%3Ab001&dur=232.153&lmt=1543880867542990&id=o-AHuJl6ojxVLHderG-brdugAe-S_R2eet7WlUdu4d2PxL&itag=36&requiressl=yes&ipbits=0&mn=sn-ab5l6nsk%2Csn-vgqsrnes&mm=31%2C26&ms=au%2Conr&ei=OTE6XLKnGoL78wSJnZy4Aw&mv=m&mt=1547317447&expire=1547339161&initcwndbps=163750&gir=yes&pl=49&source=youtube&gcr=us&c=WEB&mime=video%2F3gpp&fvip=4&sparams=clen%2Cdur%2Cei%2Cgcr%2Cgir%2Cid%2Cinitcwndbps%2Cip%2Cipbits%2Citag%2Clmt%2Cmime%2Cmm%2Cmn%2Cms%2Cmv%2Cpl%2Crequiressl%2Csource%2Cexpire&clen=6276228&signature=343BD8FC783569E1560A5E3221E8C9A6E0FC016F.86A147D8320AA3493FE0AC2CA8B5FCFD6155E767 failed. watch
All candidate resources failed to load. Media load paused.`

**Comment by omarroth** [comment] 2019-01-12 18:39
For some videos YouTube restricts the playback to the region where the video info was requested, which will be the US in this case, since that's where Invidious is hosted. I mention a fix in #92 that I'm still working on rolling out. See if changing `preferred video quality` to `dash` allows you to watch the video.

The original issue appears to have been with invalid signatures, which should be fixed. If using the fix I just mentioned allows you to watch the video, then I'll probably close this in favor of #92.

**Comment by alex9099** [comment] 2019-01-12 18:42
I see, but why would that video be restricted? anyway, isn't there an error that invidious shows if the video is actually blocked in USA?

Btw there is "Blacklisted regions: BF, BN, BY, GL, IO, KP, NP, SS, UM, UZ, VI " any of those is where the server is hosted?

**Comment by omarroth** [comment] 2019-01-12 18:52
It seems fairly arbitrary, but the issue is generally not that a video is blocked in the US, it's that users outside of the US are not able to watch the video, since the video was requested from a US IP.

From a US IP, I can view the video links you posted fine.

**Comment by alex9099** [comment] 2019-01-12 18:56
Hmm i see, so newpipe and youtube-dl (for example) work because it is the client that makes the request of the video file with it's own IP?

What is necessary to do the request? does the youtube page get loaded and javascript executed?

**Comment by omarroth** [comment] 2019-01-12 19:01
> Hmm i see, so newpipe and youtube-dl (for example) work because it is the client that makes the request of the video file with it's own IP?

That's correct. 

> What is necessary to do the request? does the youtube page get loaded and javascript executed?

It usually needs to pull `/get_video_info` and `/watch` to get everything it needs and doesn't execute any javascript. For region locks it will try to use various proxies to get what it needs. 

For the linked issue, I suggest proxying everything as a solution (which is partly what it does already), so I don't expect this to be as much of an issue in the future.

**Comment by omarroth** [comment] 2019-02-28 02:09
Since the original issue with invalid URLs appears to be fixed, I'm going to close this.

The other discussion here will be better in #92. As mentioned I'm slowly working on proxying everything. In the meantime `&quality=dash` will fix most issues where playback fail because of a 403.

**Closed by omarroth** 2019-02-28 02:09 UTC

**Comment by DrDonkey** [comment] 2019-03-10 04:03
Yeah, I think it's because of the quality too. I tried https://invidio.us/watch?v=m7Bc3pLyij0&quality=dash video on Freetube and it loaded 480p, there was no 720p option.

**Comment by jeroen7s** [comment] 2019-04-30 07:39
i'm still getting this error, on https://invidio.us/watch?v=Tztc73r8348
why was this closed? was it fixed?

**Comment by gloschtla** [comment] 2019-05-26 16:23
This error still occures, even though the video is available!

https://invidio.us/watch?v=7dt2mIgZTfA

**Comment by Perflyst** [comment] 2019-05-26 16:24
Please try https://invidio.us/watch?v=7dt2mIgZTfA&local=true or https://invidio.us/watch?v=7dt2mIgZTfA&quality=dash

Video works for me, is probably #92

**Comment by gloschtla** [comment] 2019-05-26 16:27
> Please try https://invidio.us/watch?v=7dt2mIgZTfA&local=true or https://invidio.us/watch?v=7dt2mIgZTfA&quality=dash
> 
> Video works for me, is probably #92

Now it works for me as well. 
I suggest to add this troubleshooting hint directly on invidio.us

**Comment by Perflyst** [comment] 2019-05-26 16:28
For things like this, I think it is better if you join our matrix channel at https://riot.im/app/#/room/#invidious:matrix.org or on freenode irc #invidious

**Comment by omarroth** [comment] 2019-05-26 16:37
I agree it makes sense to provide it elsewhere though. Maybe linking to some troubleshooting tips in the [wiki](https://github.com/omarroth/invidious/wiki).

**Comment by cylgom** [comment] 2019-09-21 09:13
This really annoyed me so I made [a quick-and-dirty™ greasemonkey script](https://greasyfork.org/en/scripts/390358-invidio-us-auto-dash) to automatically append quality=dash when this error occurs. Not ideal but at least it uses MutationObserver :)

**Comment by olof-nord** [comment] 2020-02-09 16:47
Adding `&quality=dash` to the URL did the trick for me

**Comment by thiswillbeyourgithub** [comment] 2020-08-07 09:44
For those who don't want to install greasemonkey and such, using the addon "redirector" on firefox did the trick to add `&quality=dash` to the end

**Comment by thiswillbeyourgithub** [comment] 2020-08-10 18:51
Update : turns out that adding `&quality=dash` was not reliable for me.

But, in my case : the error was simply due to not toggling on "proxy mode" in the addon [firefox addon invidition](https://addons.mozilla.org/en-US/firefox/addon/invidition/)
