### ISSUE TITLE
[RFC] Friendlier Front Page

### ISSUE THREAD

**Issue by callum1993** [omarroth/invidious#217] opened 2018-11-04 19:38 UTC
Hi, I'm a big fan of invidio.us, and I hope this RFC can help in getting it more popular. 

The front page (top videos) is full of videos by extreme right channels, among others "Paul Joseph Watson", "Jair Bolsonaro", "Styxhexenhammer666" \[1\]. __I believe that this deterring potential users.__ A short look in the code (very readable, big cudos!) it looks like you are displaying videos from a database of videos already watched on invidio.us. 

One solution to friendlier recommendations would be to pull in recommendations from YouTube's "Home" and/or "Trending" pages. I've noticed some functions in `src/invidious/jobs.cr` suggesting you are already crawling some parts of YouTube, but I haven't fully analyzed them. 

I'd love to hear your feedback on this, and maybe we can come up with more ideas together. If you prefer to discuss this in private, please feel free to send me an email at callum.1993 (a) outlook.com

\[1\]: I've noticed that today they are penetrating the front page less, but it has been a problem with the above and other channels ever since I started using invidio.us.

**Comment by omarroth** [comment] 2018-11-05 04:30
Hi! I'm very happy to hear you found it easy to read. For others that would like to see how Invidious selects videos that go on the front page, I'd recommend taking a look [here](https://github.com/omarroth/invidious/blob/master/src/invidious/helpers/helpers.cr#L66-L68). I think that the algorithm is fairly content-neutral, so I think it's unfortunate that the front page has videos that people might find objectionable, and I can absolutely see that being a turn off. 

The trending looks good from a cursory glance, and is already the default homepage for NewPipe and FreeTube if I recall correctly. You're right that Invidious crawls other parts of the site, and it actually already pulls the `Trending` page elsewhere, so I can see that being the drop-in solution. 

I would also be interested to see if there's a better way to rank the videos that Invidious stores, and I'd absolutely appreciate other folks' thoughts on this as well.

**Comment by callum1993** [comment] 2018-11-05 11:36
The algorithm invidious uses to rank videos itself is pretty good, the problem stems from the videos it (currently) draws from. If invidious can attract a more diverse user base (and thus a more diverse selection of videos), this problem will then solve itself in the future. Until then, feeding the front page with some known-good (for some definition of "known-good") videos is IMO a nice stop-gap. 

Yes, NewPipe uses the trending page. There is [some discussion][1] about refining it here, but it's relatively new. 

Regarding ranking videos stored by invidious: again, I don't think there is anything particularly wrong with The Algorithm, it just needs more data. Filtering by language (user agent string usually contains one) seems like a good idea in general though.

PS: I've just thought about this: __/r/videos__ (or __/r/videos/top__) might be suited for the front page as well and maybe more interesting than Youtube's Trending for some.

PPS: I don't know Crystal in particular, but maybe I can help in other ways (general programming/parsing stuff, HTML/JS/CSS, etc.)

[1]: https://github.com/TeamNewPipe/NewPipe/issues/1805

**Comment by dimqua** [comment] 2018-11-05 21:45
I vote for Trending by default and /r/videos as an option to registered users.

**Comment by omarroth** [comment] 2018-11-07 04:48
That's why this is an RFC, so people can voice their concerns. You shouldn't feel that your words have no effect. I, and I'm sure many others, appreciate your thoughts. I see this is a proposal for adding content that more people would find more interesting, and how best to find that content. If you have any thoughts on how that could be improved, please feel free to share them.

There is no need for this to be politically-charged. Again, the goal here is to provide interesting content for users on the site. It might be more productive therefore to rephrase this issue as "More Engaging Front Page". Obviously some content isn't very engaging to some people, such as the videos that @callum1993 mentioned. It would also be nice to have content that better represents what people watch on Invidious. Keep in mind that videos on Invidious are ranked based on stats from *YouTube*, not on Invidious itself, so improvements could be made there, especially since Invidious itself doesn't have any system for allowing users on the site to choose the content they want to go on the front page, except for their subscriptions.

An alternative might be to pull most recent videos from the `x` most subscribed channels on Invidious. This would likely more accurately reflect what users watch on the site, since it's a small snippet of what most users want in their feed. From a quick look, the videos on the front page would be from:
```
UCXuqSBlHAE6Xw-yeJA0Tunw - Linus Tech Tips
UCsvn_Po0SmunchJYOWpOxMg - videogamedunkey
UC-lHJZR3Gqxm24_Vd_AJ5Yw - PewDiePie
UCsXVk37bltHxD1rDPwtNM8Q - Kurzgesagt – In a Nutshell
UC6nSFpj9HTCZ5t-N3Rm3-HA - Vsauce
UCAL3JXZSzSm8AlZyD3nQdBA - Primitive Technology
UC2C_jShtL725hvbm1arSV9w - CGP Grey
UCBJycsmduvYEL83R_U4JriQ - Marques Brownlee
UCDWIvJwLJsE4LG1Atne2blQ - h3h3Productions
UCBa659QWEk1AI4Tg--mrJ2A - Tom Scott
UC9-y-6csu5WGm29I7JiwpnA - Computerphile
UC3XTzVzaHQEd30rQbuvCtTQ - LastWeekTonight
UCHnyfMqiRRG1u-2MsSQLbXA - Veritasium
UC4USoIAL9qcsx5nCZV_QRnA - iDubbbzTV
UC6107grRI4m0o2-emgoDnAA - SmarterEveryDay
UCUHW94eEFW7hkUMVaZz4eDg - minutephysics
UCdJdEguB1F1CiYe7OEi3SBg - JonTronShow
UCJkMlOu7faDgqh4PfzbpLdg - Nerdwriter1
UC0vBXGSyV14uvJ4hECDOl0Q - Techquickie
UCq6aw03lNILzV96UvEAASfQ - bill wurtz
UC9RM-iSvTu1uPJb8X5yp3EQ - Wendover Productions
UCr3cBLTYmIK9kY0F_OdFWFQ - Casually Explained
UCLx053rWZxCiYWsBETgdKrQ - LGR
UCoxcjq-8xIDTYp3uz647V5A - Numberphile
UCL_f53ZEJxp8TtlOkHwMV9Q - Jordan B Peterson
UCjFqcJQXGZ6T6sxyFB-5i6A - Every Frame a Painting
UC8uT9cgJorJPWu7ITLGo9Ww - The 8-Bit Guy
UCwmFOfFuvRPI112vR5DNnrA - Vsauce3
UCR1D15p_vdP3HkrH8wgjQRw - Internet Historian
UCrTNhL_yO3tPTdQ5XgmmWjA - RedLetterMedia
UCUK0HBIBWgM2c4vsPhkYY4w - The Slow Mo Guys
UCR1IuLEqb6UEA_zQ81kwXfg - Real Engineering
UCLXo7UDZvByw2ixzpQCufnA - Vox
UC0M0rxSz3IF0CsSour1iWmw - Cinemassacre
UCC552Sd-3nyi_tk2BudLUzA - AsapSCIENCE
UCqmugCqELzhIMNYnsjScXXw - Vsauce2
UCzUV5283-l5c0oKRtyenj6Q - Mark Dice
UCYO_jab_esuFRV4b17AJtAw - 3Blue1Brown
UCJHA_jMfCvEnv-3kRjTCQXw - Binging with Babish
UCEOXxzW2vU0P-0THehuIIeg - CaptainDisillusion
```

**Comment by indexitis** [comment] 2018-11-07 05:31
>An alternative might be to pull most recent videos from the x most subscribed channels on Invidious.

I can get behind this. I just want to make sure we're not excluding certain channels based on political views. All content could be disagreeable to _some people_, or put another way, there's no content that everyone will find engaging. A content-neutral popularity contest like you proposed seems like a fine compromise.

**Comment by zipline808** [comment] 2018-11-07 06:09
I created this account specifically to reply here as I worry that politics might be worming its way into places it has no business being.

A long while ago I completely abandoned all Google products because I grew tired of their ceaseless efforts to force politics down my throat. I became tired of seeing the blatant political bent across the board when not signed in to a Google account; I became equally tired of having my ego massaged by the echo chamber Google wished to create around me when I was logged in to my account in order to maximise views and view time. I'm a grown-up, I do not need nor do I ever want some ethereal entity curating the material that I ingest. I discovered HookTube and so I moved over to that and was happy to escape the sickly influence of Google's invisible hand. After HookTube was destroyed I moved over to Invidious and, as with HookTube, I appreciate that Inividious does not try to make decisions on my behalf. I like to be left alone.

I really do not wish to wander down the path of political discussion on here but I think I must in order to properly explain my views on this matter; I will do my best to not start fires. Callum states that the channel "Jair Bolsanaro" is a channel that is deterring potential users, but what if said potential user is Brazillian? It does not matter if said Brazillian likes, dislikes, or is indifferent to Mr. Bolsanaro they should not be excluded from having media relevant to them included in the home page of a media oriented and international website. I'm not saying that Invidious should purposefully include media relevant to Mr. Bolsanaro on the home page, I'm just saying that Invidious shouldn't purposefully exclude such media from the home page. Callum has the choice to not watch videos about Mr. Bolsanaro but if such media is curated away from the home page then everybody else is robbed of that same choice.

To create a more engaging home page necessarily requires some personalisation because what engages you might bore me, vice versa. Therefore if the home page is altered to be more agreeable to one group of people it will mean it becomes disagreeable to another group of people. I vote that the home page be left alone, it is fine as it is. Sometimes there are good things there, sometimes not. You win some, you lose some. If people wish to have a more personalised and engaging home page let them have a personal home page unique to their account and their subscriptions and leave the global home page alone so that those of us without accounts don't have to deal with the drivel that other people enjoy.

I don't know how to quote others so please forgive me omarroth, but in your previous reply you said that *an alternative might be to pull most recent videos from the x most subscribed channels on Invidious*. I take issue with this. I take issue with this because popularity does not necessarily mean enjoyability; I'm sure Pewdiepie irritates as many people as he entertains for example. The current home page gives us a selection of videos from unknown creators who might be overlooked otherwise, it gives us some videos from popular creators too, it gives us videos in other languages which is quite important because not everyone speaks English, and it gives us an opportunity to enjoy unexpected content. Having the home page filled with what is popular does nothing but lock people in to consuming much the same content cyclically. Plus, everyone knows the big channels and can find them with a search very easily.

In closing I vote that the global home page be left alone and that any and all curation occurs only on personal home pages and subject to a series of user configurable options. Please don't bring back the invisible hand that I fled before.

**Comment by hugoabonizio** [comment] 2018-11-07 11:12
@zipline808 Bolsonaro is a dictator wannabe, he popularity grew up exactly on this kind of collateral exposition. He begins as a meme, a joke in Brazil, but on a crisis enviroment part of the population thought his retrograde ideas might make sense. Please, don't endorse it.

I liked @omarroth's ideia!

**Comment by hugoabonizio** [comment] 2018-11-07 11:56
@StephenLynx I won't discuss theology with you, believe on what you want. This is not the right place, let's keep the focus on the OP's request please.

**Comment by GithubIsAwful** [comment] 2018-11-07 13:44
@hugoabonizio very weird to start politicising the debate, and immediately attempt to shut it down when responded to. Maybe you should stick to YouTube.

**Comment by dimqua** [comment] 2018-11-07 15:04
@omarroth I don't want to see "recommended" videos in languages I don't even understand. Sadly, the Invidious' user base is just too small to supply a variety of videos in languages other than English.

**Comment by zipline808** [comment] 2018-11-07 17:53
@hugoabonizio For the sake of argument I will say that Mr. Bolsanaro is a dictator and considering he is a dictator that is dangerous to the Brazillian people it makes sense then that the Brazillian people are not excluded from content regarding Mr. Bolsanaro. How do the Brazillian people know what atrocities to prepare for if they're precluded from fair access to relevant media? Surely then it is in the best interests of the Brazillian people to ensure they have fair access to such media; their lives depend on being in the know.

This is nothing more than attempted political censorship. It has no business here.

**Comment by hugoabonizio** [comment] 2018-11-07 19:28
@zipline808 following the same logic, censoring Ku Klux Klan supporting videos would be political censorship too? (by the way Bolsonaro is supported by [KKK former leader](https://www.bbc.com/portuguese/brasil-45874344))

I think some kind of curating might add value to the home page.

**Comment by zipline808** [comment] 2018-11-07 19:45
@hugoabonizio Yes, it would be political censorship and it would also be dangerous because it would prevent the black population of America from being up-to-date with the activities and intentions of the KKK, and without the most up-to-date information about the KKK's activities they would not be able to protect themselves most effectively. The KKK's videos might upset black Americans but having free access to that media ensures that black Americans can always be ready for any potential threats to their wellbeing. And so the same applies to Mr. Bolsanaro and Brazillians; if the man is a threat to their wellbeing it is in their best interests to be able to easily keep up-to-date with his activies and the purposeful censorship of videos regarding Mr. Bolsanaro would negatively impact their ability to employ forethought to the betterment of their wellbeing.

**Comment by Discookie** [comment] 2018-11-07 23:58
What do you think about generating 2 front pages, like Reddit? One with the larger political channels filtered, and one with everything included.
(Obviously there will be subjectivity, but it might be possible to just filter everything 'News', and don't touch individual channels at all.)

I've opposed it back when they proposed the idea, but taking a break from politics is sometimes very much needed, and if the first thing that's visible is politics, some people will be turned away by the site, no matter what type of content they see.

Or hell, even having a basic filter for YouTube categories would be sufficient, such as: "Filter Music / Filter Gaming / Filter News" - this could be passed by the URL without any Javascript (eg. `&filter=news,gaming`)

I'm not sure what kind of videos I'd like to see on the front page, but politics is one I know for a fact wouldn't make me stay.

Also, I like @dimqua's idea of a language filter - you could choose to display videos whose languages are originally English or your local language - but I'm not sure I'd want to have it on by default.

**Comment by zipline808** [comment] 2018-11-08 00:41
@Discookie It seems more work than is necessary when one can simply choose what to watch and not watch. If a political video on the home page is not to someone's taste then they can move on. I understand that taking a break from political stuff is important but the responsiblity to care for one's own mental wellbeing is on them, not on the people who work freely to provide them media. If someone is so lacking in self control that they cannot help but click on videos they know will annoy them then who's fault is that? And if someone is so easily displeased that simply seeing the thumbnail and title to a video they might not like makes them angry then no amount of prostration will ever sooth their ills.

Right now on the home page I see some videos about politics, gaming, biking, music, history, science and vlogging. That seems a remarkably varied selection of videos to put up on the home page; something for most people. If you pay attention to the words of those who are arguing most energetically in favour of curation you'll see that their issue is not that there is too much political stuff on the home page, rather it is that the political stuff on the home page is of a political sort they disagree with. This is all masked nicely in the idea of creating a more "friendly" home page but the reality is just an attempt at political censorship and it ought not be entertained. A personal home page that is curated according to a user's account and settings is of no issue, but these people are arguing for changes to the global home page because they're not adult enough to move on past things they don't like.

As for the suggestion of a welcome message and tips, I agree. Though I would suggest putting usage tips on a help page navigated to by a help button placed next to the login button. Having usage tips right on the home page might become a nuisance after a while - HookTube had similar and I got annoyed at its presence on the home page quite quickly because it pushed the grid of suggested videos down and hid many beyond the bottom of the screen and that's a great nuisance on a laptop.

**Comment by dimqua** [comment] 2018-11-08 01:48
> if the first thing that's visible is politics, some people will be turned away by the site

Yeah, but if they're going to watch some political news, they'll be disappointed. :-D

> you could choose to display videos whose languages are originally English or your local language

You can have both! :-)

**Comment by dimqua** [comment] 2018-11-08 01:51
I'm not familiar with `/r/videos`, does it include political videos?

**Comment by omarroth** [comment] 2018-11-08 02:54
> To create a more engaging home page necessarily requires some personalisation because what engages you might bore me, vice versa. Therefore if the home page is altered to be more agreeable to one group of people it will mean it becomes disagreeable to another group of people.

I don't think this is necessarily true. The reasoning behind my proposal was to provide a sampling of content so there might be at least one thing that someone would find interesting. I understand your fear of having an invisible hand deciding what you should watch, and that is why we are discussing this here.

> The current home page gives us a selection of videos from unknown creators who might be overlooked otherwise.

Currently videos on the front page are already ranked in large part by popularity, so if there are relatively unknown videos on the front page that would be by accident, rather than by design. If there is a way of finding such videos, then I would appreciate hearing it. Otherwise, I don't see my proposal as much different in that regard, except that it would better reflect popularity on Invidious, rather than on YouTube.

What I propose [here](https://github.com/omarroth/invidious/issues/217#issuecomment-436503761) appears to have received quite a bit of support, including from the user who had similar concerns to @zipline808. I would like to move forward with implementing it, but obviously I would still like to hear thoughts about how the front page could be improved.

**Comment by zipline808** [comment] 2018-11-08 06:17
This [proposal](https://github.com/omarroth/invidious/issues/217#issuecomment-436503761) seems fine, reflecting the interests of Invidious users is sensible.

There has been two parties in this conversation advocating for changes to the home page: one which just wants more relevant videos, such as in the aforementioned proposal, and the other which wants explicit political censorship. I felt that the aggressive calls for censorship were steering the discussion on what changes to implement and so my equally aggressive and political responses were an effort to highlight the absurdity of the calls for censorship and to force a non-political justification for changes. I do not know what sort of person you are @omarroth but I have seen many projects go down the drain because those in charge were people pleasers who chose to please people who took a mile when given an inch. I wanted the anti-censorship side of the fight to have the loudest voice.

I no longer feel worried about censorship on Invidious.

**Comment by BriannaColeman** [comment] 2018-11-08 07:34
@hugoabonizio Please go see a doctor.

**Comment by Discookie** [comment] 2018-11-08 11:15
@zipline808  
While the people's intentions arguing in favor of political censorship might be politically motivated, I don't think it's fair to dismiss the idea entirely. Let's face it: In our current political climate, the subject is very divisive. The chance that someone will be turned away by a political video is very high, whether they watch it or not - even if they don't click it, sometimes the videos themselves, be it because of the uploader or because of enraging titles/thumbnails, can drive people away.  
Personally, after seeing too much political content, I get exhausted and simply leave the site. Of course, content I disagree with frustrates me more, but content I agree with can have the same effect. It's not as simple as "they are not adult enough" - obviously my mental health is my responsibility, and I'll avoid sites that have a bad effect on me, but not clicking a video doesn't mean it doesn't affect me - not at all.  


I'm kind of disappointed that my suggestion of filtering by Youtube categories flew under the radar. It provides a reliable way to filter out a specific type of content, without any special treatment, using publicly available information. It doesn't even have to be politics necessarily - it can be any category you don't like. You mentioned Gaming in your earlier comment - good thing there's a Gaming tag you could filter out to hide all such content!  
Even if the current front page remains unchanged, I think filters would be a good addition - not censoring content by default, but providing the ability to do so reliably.

And in the end, it comes down to the ability to make a choice. If you do end up changing how the front page is displayed by default, there should always be an option to revert that, one that is accessible without login. However, your concerns are valid, and I'd understand if the front page was left as it is. I still think that you should have the ability to hide such content, be it via filters, or a predefined list of 'best' channels. After all, if people want a friendlier front page, we should let them choose to have it, even if it's behind a click or two - but not behind a login-wall.

@omarroth's suggestion is one I wouldn't mind having, but I also don't think it's the best option available. Showing only the top channels ignores many essential parts of a good front page - @zipline808 already highlighted that popularity doesn't mean enjoyability, and I reckon it would kill 'viral' or 'rising' videos altogether, cutting off a huge chunk of popular content.

**Comment by 99883311** [comment] 2018-11-08 15:58
This conversation is a mess. No one is being forced to view the home page. Indeed, if someone is really triggered that much, I'd suggest bookmarking any random page, the search bar is still usable (`https://invidio.us/a`). Calls for political censorship  are absurd and point to reification inherently - you can not claim to be pro-users and stab them in the back in the same sentence (some will take this literally, it is their problem). Changes made through a political proxy inevitably support a political position and lead to further censorship for the same. So is being political the problem here? No. You're looking under the wrong light. The problem here is being _pro-users_. The primary goal of OSS isn't catering to the users via the developer or abandoning their wishes for the same -- it is the ability for users to make their own changes and host their own code instances and run them independently. These positions about suggested videos are relevant neither from a technical standpoint nor from a usage standpoint, for these are not bugs. They are positions espoused by other users fiddling with someone else's unforced positions, like reporting someone else's crimes before committing the same, if you will. Invidious does not inherently support those websites - they are not found anywhere in the code. Removing these suggestions for something that spares the subjective feelings of someone else would be a major loss for the project and would be alike to committing a crime after being wrongly convicted for the same.

So, there are two choices here - either invidious can completely remove the suggestions feature, and cater to this issue and play no hands, or it can do nothing and let things continue as they are, and people in disagreement can type two extra characters after the url to quench their disagreements.

If anything is not clear, I'd suggest you to read my text over again at least twice, and then post a proper reply. Snide remarks and intentionally misleading conversations are to no one's benefit.

**Comment by Discookie** [comment] 2018-11-08 18:54
Have you read the third paragraph of my last reply? I am fine with making the front page stay as it is! I'm just all up for giving users a way to get away from some types of videos, even when they are not logged in. And for it to be reversible. That's the only change I am suggesting.

But honestly, you are right. We *can* host our own code, we *can* make our own changes, we *can* go so far as to create an account on the original site. But when you just found a new 'youtube-clone', the first thing you do isn't gonna be creating a new Docker instance, and fiddling with the code just so you can avoid content that *drove you away from the site in the first place*. And that's what we are discussing here.

I have nothing more to add to this conversation. I stand by changing the front page somewhat, be it filters or omar's suggestion. The 'News & Politics' category does not differentiate between parties, groups, or the like.

Perhaps there was a language barrier when I used political censorship. I now realize it implies removing everything *I don't like* under the blanket label of 'Politics'. I never meant it that way. I'm sorry about that.

**Comment by dimqua** [comment] 2018-11-08 22:23
> but content I agree with can have the same effect

I don't understand it honestly, but I agree with your suggestion.

It's not enough to simple have most relevant videos (according to some algorithm) listed on the front page, since different people have different preferences. The one may like gaming or sports videos, for example, but the other one don't (doesn't matter how many likes and views these videos have).

**Comment by omarroth** [comment] 2018-11-09 03:05
There's now a preview of [this](https://github.com/omarroth/invidious/issues/217#issuecomment-436503761) proposal available at https://dev.invidio.us. Currently, it pulls videos from the top 40 most subscribed channels on Invidious, sorted by date. I expect to make a couple changes before pushing it to the main site, and expect for future comments on this issue to directly respond to or raise concerns related to this proposal.

> I'm kind of disappointed that my suggestion of filtering by Youtube categories flew under the radar.

Sorry about that. I think language filters, content filters (news, gaming, etc) and the idea of having a seperate or alternate front page would do well as a new issue. @callum1993 mentioned discussion in TeamNewPipe/NewPipe#1805 about support for the various trending pages, which I think already implement quite a few of the ideas proposed by @dimqua and @Discookie, as there are different trending pages in various countries. I can see it being mostly straightforward to add support for users that wanted to view trending videos in a different language.

The concern about killing off 'viral' or 'rising' videos is completely understandable, and very similar I think to what @zipline808 mentions [here](
https://github.com/omarroth/invidious/issues/217#issuecomment-436515160). I think that's the goal that YouTube attempts to solve with their Trending pages (whether successful or not), and would at least partially solve the issues mentioned above.

I would very much like to have a new issue to discuss this.

> The primary goal of OSS isn't catering to the users via the developer or abandoning their wishes for the same -- it is the ability for users to make their own changes and host their own code instances and run them independently.

I think having this discussion is another way for users to make their own changes (or at least petition), although it relies on someone who can implement them.

There's still quite a bit left to respond to. For anything directly related to bugs or proposed features I would recommend opening a new issue so it can be properly addressed. For everything else, feel free to contact me at omarroth@protonmail.com or on the [FreeTube Matrix Server](https://riot.im/app/#/room/#freetube:matrix.org).

**Comment by 99883311** [comment] 2018-11-09 04:10
@Discookie You're misinterpreting me (intentionally or otherwise). Doing it under the guise of altruism does not make it any better. I suggest you read my reply again. And no, I didn't write that long post for you or for anyone else, I wrote it to resolve the issue.

@omarroth 

> I think having this discussion is another way for users to make their own changes (or at least petition), although it relies on someone who can implement them.

That is not how it works. Stop skirting around the issue.

**Comment by omarroth** [comment] 2018-11-09 04:53
As it stands, the issue is that your comments are off-topic. You are not resolving anything by making accusations targeted at me or a productive contributor.

I suggest you re-read [my proposal](https://github.com/omarroth/invidious/issues/217#issuecomment-436503761) or previous comment, or look at the proposed changes [here](https://github.com/omarroth/invidious/commit/81d372034f784fbec330cb08ed7939e9f5c13d2f). If you have any thoughts on how it could be improved, feel free to share them.

**Comment by cloudrac3r** [comment] 2018-11-09 09:56
[Why don't we have both?](https://cadence.moe/api/images/8de452)

As it stands, one person likes politics and another person doesn't. I can appreciate both of these perfectly valid and reasonable views. My suggestion is to set a browser cookie depending on the user's personal preference of what to do with the front page, (could look like `frontpagemethod=1`) and when this cookie is sent to Invidious along with the rest of the request for the home page, Invidious can return results according to the selected algorithm.

### Suggested algorithms

Trending. This is curated by YouTube itself — [while the content might not be particularly interesting,](https://github.com/omarroth/invidious/issues/217#issuecomment-436860384) and while censorship issues *definitely* come into play, I think a curated front page would be the most appealing way to welcome new users to Invidious. I suggest that this be the default view, but I'm not particularly bothered, since the whole point is that it's customisable.

Videos from popular channels as suggested [earlier in this thread](https://github.com/omarroth/invidious/issues/217#issuecomment-436503761). I personally really like this idea, but I can understand not wanting to lose the current method, which is why we finally have:

Popular videos from the whole site, as per the current algorithm.

A blank page.

The user's subscription feed, if they're signed in.

### Switching algorithms

As per Discookie's suggestion [earlier in this thread](https://github.com/omarroth/invidious/issues/217#issuecomment-436827896), you could add a banner reminiscent of HookTube's on the top of the front page. This could additionally detail the sorting algorithm to use, from "Trending", "Popular channels", and "Popular videos". Clicking a link would set that cookie and reload the page to display the new algorithm.

Of course, this could also be changed from the settings menu.

While this would introduce more work for our good friend omarroth, I don't expect it would be much more involved than simply rolling with his popular channels suggestion further up. The code for YouTube's "trending" is mostly already there, the existing algorithm is obviously completely already there, which just leaves the code for popular channels which would have to be implemented anyway.

While the details of which algorithm should be the default have yet to be considered, I think that giving users the choice of algorithm is totally in-line with Invidious's maxims and is opinion-agnostic, featureful, and the best option available

**Comment by Discookie** [comment] 2018-11-09 11:30
Thanks for the clear and concise write-up!

I think alongside cookies, it's better to have separate pages for separate algorithms. That way, they could be bookmarked if an user likes to browse 2 types of feeds.
Eg. Their cookie is set to `frontpagemethod=trending`, but if they'd like to look at the `top40` channels' feed without changing their sort, they could do that by going to `invidio.us/?method=top40`. And they could change their cookie via an AJAX.

I think the best way to go about this would be having a 'tabs' bar under the search bar, with links to each page. (Only visible on the homepage, of course.) And in each method's tab, there should be a `Set as default` button, similar to a `Subscribe` button in looks.

(Sidenote: We need a better word than `method` to describe the feed type :D)

**Comment by cloudrac3r** [comment] 2018-11-09 22:03
> (Sidenote: We need a better word than `method` to describe the feed type :D)

`algorithm` works.

**Comment by elypter** [comment] 2018-11-15 04:08
>The front page (top videos) is full of videos by extreme right channels

hooktube had(and probably still has) the same problem. i dont know how hooktube works but i assume it has something to do with the fact that alternative platforms attract an overly proportional amount of those people because their content in banned or unwanted on mainstream platforms. alternative platforms are often more open and rightly so. unfortunately that means that they get drowned in that content and then lose the appeal for everyone else. invidious is not hosting content so this doesnt directly apply but the overall tendency and awareness in that group probably still makes them more likely to favor alternative solutions, especially if they see the hosting company(google) as a political enemy.

another factor is that there are groups forces that want this content to be pushed und who know how to work the algorithms.

i would suggest to use as many feeds as possible and as diverse as possible and then let the user decide which feeds he prefers and/or automatically show those more often that the user chooses.
feeds can be general statistics based(youtube frontpage), moderated(reddit.com/r/videos), usage based(related channels), or curated(favorites of a conneseur). the more diverse the more robust and the less likely that a user will find nothing interesting on the page.

**Comment by elypter** [comment] 2018-11-15 04:31
> I don't want to see "recommended" videos in languages I don't even understand.

i think this is important. even if most users dont understand it, the fact that it made it to the front page means that it is quite important for someone speaking that language. i also dont think users should be presented a different startpage depending on his geolocation or browser language. i think it doesnt really harm to see a video that you can quickly identify as foreign language because you either scroll over quickly or its your language. what i could imagine is if there are different language variants like with wikipedia that you can go to deliberately.

**Comment by elypter** [comment] 2018-11-15 04:41
> I'm not familiar with `/r/videos`, does it include political videos?

no. political videos are against the rules. probably because of the drama and off topicness. i think it is an ok source but doesnt quite catch all the variety of content.

**Comment by dimqua** [comment] 2018-11-15 10:22
> I also dont think users should be presented a different startpage depending on his geolocation or browser language

Geolocation? Sure. But what is wrong with browser language?

**Comment by elypter** [comment] 2018-11-15 18:42
most content and also most good content is in english. there is good content in other languages as well but it might not be enough to be viable as the sole content for the average visitor. the smaller the country/native speakers the more pronounced this gets. however i would enjoy having a link to a language version based on location guessing or a section on the frontpage that you can collapse. this could also not only contain videos in your language but also videos that are about your region or are from youtubers of that region even if they make english videos. but all that should be optional and you should be able to change it so if you are a person living in a foreign country you probably want to be able to choose between your home country, your current country and international.

**Comment by dimqua** [comment] 2018-11-15 19:34
> most content and also most good content is in english. there is good content in other languages as well but it might not be enough to be viable as the sole content for the average visitor.

Yes, but like I said earlier, you can have both types of content (in English and in your "preferred" language) at the same time. Your preferred language can be chosen automaticly based on your IP and User Agent of your browser. 

However, with `/r/videos` as a source you can get videos only in English.

**Comment by elypter** [comment] 2018-11-15 20:12
>Yes, but like I said earlier, you can have both types of content (in English and in your "preferred" language) at the same time. Your preferred language can be chosen automaticly based on your IP and User Agent of your browser.

i am not really fixed on this. i am fine as long as things dont get shoved onto you just because of your ip or os settings. as long as the user is in control and the defaults give reasonable results i am ok with it

>However, with /r/videos as a source you can get videos only in English.

you could also crawl local subreddits and look for youtube links. in fact you could combine a whole lot of subs into a combined "reddit" tab. there are many videos posted outside of /r/videos and some are focused on very specific topics which can be a good supplement for youtube categories

**Comment by cloudrac3r** [comment] 2018-11-16 05:45
I think the option to either enable or disable any potential region-specific features would be an excellent idea.

**Comment by elypter** [comment] 2018-11-16 16:03
but if it is on the user should be able to choose the region

**Comment by nchristensen** [comment] 2019-09-12 04:22
> Your preferred language can be chosen automaticly based on your IP and User Agent of your browser.
Please do not use IP address. For users behind a proxy or VPN, accessing through Tor, or simply visiting a foreign country this will give undesirable results.

> i think this is important. even if most users dont understand it, the fact that it made it to the front page means that it is quite important for someone speaking that language.
Agree! I actually enjoy seeing the videos in other languages. It has exposed me to a lot of content I would not have seen otherwise.

**Comment by omarroth** [comment] 2019-10-21 02:44
`Popular` is now the default for the official instance. For users that still prefer `top`, it provided in the feed menu (accessible under `/feed/top`), and can be configured as the default homepage under `/preferences`.

Cheers.

**Closed by omarroth** 2019-10-21 02:44 UTC
