### ISSUE TITLE
I install all thinks.but my website is opened like this : http://162.208.11.28 .please help me

### ISSUE THREAD

**Issue by xezerr** [omarroth/invidious#212] opened 2018-10-31 13:42 UTC

**Comment by omarroth** [comment] 2018-10-31 14:49
I just updated the [README](https://github.com/omarroth/invidious/blob/master/README.md) to include install instructions for Ubuntu. Without more information, this appears to be a duplicate of #209. Feel free to reopen if you believe this is a new issue, otherwise I would recommend looking at #209 for more information or asking questions there if you are still having trouble using the project.

For now though I'm closing this in favor of #209.

**Closed by omarroth** 2018-10-31 14:49 UTC
