### ISSUE TITLE
Subscriptions folders (aka Collections)

### ISSUE THREAD

**Issue by nopeac** [omarroth/invidious#1079] opened 2020-03-23 06:01 UTC
Collections were really useful back in the day. It gave the user the ability to group subscriptions by any theme of choice. YouTube eventually discontinued this, is it posible to bring it back in Invidious?

**Comment by elypter** [comment] 2020-03-23 14:43
#related: 826

**Comment by nopeac** [comment] 2020-03-24 23:23
@elypter Actually I'm talking about channels not videos.

**Comment by elypter** [comment] 2020-03-25 00:00
sorry, i meant to link to the nested playlist idea which i suggested to include channels. this would also be the base to allow multiple subscription feeds #18

**Comment by omarroth** [comment] 2020-03-26 20:56
Duplicate of #641?

**Comment by omarroth** [comment] 2020-04-09 00:28
Closing in favor of #482.

**Closed by omarroth** 2020-04-09 00:28 UTC
Labels: enhancement
