### ISSUE TITLE
Slow/unstable loading times for high quality video with proxy mode

### ISSUE THREAD

**Issue by mark9064** [omarroth/invidious#532] opened 2019-05-16 20:04 UTC
Using https://invidio.us as the instance with proxy mode and dash enabled, set to 1080p quality.

Load times for content can be really slow (~8s receiving 3MB of data, inet is ~6MB/s) and sometimes the requests take dramatically longer (more than a minute).

Example attached:
![image](https://user-images.githubusercontent.com/30447455/57883458-b6ead380-7815-11e9-82f5-3aaf8576d3f7.png)

Edit: Getting 500s for the media requests sometimes too which unrecoverably halts playback (I usually fix this by changing the quality and then changing it back)

**Comment by elypter** [comment] 2019-05-17 14:31
i think this is something that the player should be responsible for. i wished players showed buffer information instead of a fancy spinning animation. maybe check out video.js and if something like this could be achieved with the current version and if not create a feature request there

**Comment by omarroth** [comment] 2019-05-17 14:35
The issue is likely high load. Does this happen on https://dev.invidio.us or another [instance](https://github.com/omarroth/invidious/wiki/Invidious-Instances)?

**Comment by Perflyst** [comment] 2019-05-17 15:47
I also notice this on my instance. Invidious, especially with proxy enabled, needs a lot bandwidth and also a lot CPU.
This probably is just how it works

**Comment by mark9064** [comment] 2019-05-17 16:22
On another instance, it seems to be fine. I suspected it may be high load. Guess there isn't much that can be done about this?

**Comment by omarroth** [comment] 2019-05-19 00:34
Currently looking at ways to speed up the current implementation. Just pushed out ab4df7e078c0d5f9f369670cdc81c2540127e2ce which should hopefully help with this.

**Comment by omarroth** [comment] 2019-07-08 01:49
From #562:

> I've pushed out [e5fa5df](https://github.com/omarroth/invidious/commit/e5fa5df7be38d60ce9e4835bae170d805482afc0) which should improve download speed significantly. From some brief testing most files download about 10x faster (limited by local network), although I would appreciate other reports.
> 
> In short, YouTube will throttle downloads when requesting segments >10MB (see [Rudloff/alltube#217](https://github.com/Rudloff/alltube/issues/217), or [ytdl-org/youtube-dl@e4a6091](https://github.com/ytdl-org/youtube-dl/commit/e4a60912b8345536387ae14d0d0611eb0b82c23a)). For downloads this commonly results in throttling down to ~300Kb or lower.

**Comment by omarroth** [comment] 2019-08-15 14:13
Closing in favor of #616.

**Closed by omarroth** 2019-08-15 14:13 UTC
Labels: bug
