### ISSUE TITLE
Duplicate RSS entries

### ISSUE THREAD

**Issue by zorbakus** [omarroth/invidious#365] opened 2019-02-16 15:42 UTC
For all of my RSS invidio.us subscriptions, I get spammed with duplicate entries every single time I refresh in an RSS reader program. This is because Invidious gives its feed entries a "published" hour equal to the current system/local hour when retrieved, making all of those entries technically different in the RSS reader.

Example: https://invidio.us/feed/channel/UCYO_jab_esuFRV4b17AJtAw

**Comment by omarroth** [comment] 2019-02-16 17:09
Invidious pulls information for RSS feeds from the channels page currently. The issue is that YouTube does not provide a `published` date. You can see here:
![image](https://user-images.githubusercontent.com/14208607/52902524-5e387a00-31d7-11e9-8fb0-8b593384f903.png)

`1 week ago` is converted to a published time internally using `Time.now - interval`. This becomes more and more inaccurate as the interval increases, as it is rounded quite heavily.

YouTube provides a `/feeds/videos.xml` endpoint which *does* provide accurate published info, but only for the latest 15 videos.

It might be possible to find some sort of consistent published, or it should be possible to scrape the `videos.xml` page.

**Comment by omarroth** [comment] 2019-02-18 22:07
Should be fixed with 92223dbee58e4f1eecedfd41cf122a13f8c30489.

**Closed** 2019-02-21 19:38 UTC
Labels: bug
