### ISSUE TITLE
Default Highest Quality / Higher Than 1080p

### ISSUE THREAD

**Issue by Z3ROGRAV1TYx** [omarroth/invidious#935] opened 2019-11-25 20:43 UTC
Can't figure out why I can't have 1080p be the default quality?
It shows up in the player submenu, yet no option in settings to have it just set tot he highest quality it can, or even select 1080p there?

Also what is the issue that we are unable to have above 1080p? 1080p60fps, 1440p, 4k etc.?
Is this impossible to implement? Or is it being worked on? Would be a shame not to be able to have it.
Not entirely sure how Invidious is working, I know Newpipe and Smart YoutubeTV don't really have issues like this, but I also know those are clients and Invidious isn't really a "client" but instead a frontend. 

I'm just curious in the end if this will be possible to have support for higher resolutions, 60fps (and other variants) and more for Invidious in the (hopefully near?) future? As well as the ability to select higher than 720 as a default play option.

**Comment by tleydxdy** [comment] 2019-11-27 06:39
https://github.com/omarroth/invidious/wiki/Geoblocking,-available-video-quality-and-DASH

**Comment by Z3ROGRAV1TYx** [comment] 2019-11-27 14:33
> https://github.com/omarroth/invidious/wiki/Geoblocking,-available-video-quality-and-DASH
I do have dash as default video quality, but it does not seem to be seeing videos higher than 1080p.
Do I need to have proxy enabled? Maybe this is why? I know it states it proxies videos to achieve higher quality, wasn't sure if this was done in the same way as the geoblocking?

**Comment by unixfox** [comment] 2019-11-28 21:09
I have dash with 1080p available on most of my videos but I would like to set 1080p for dash by default. Currently, when using dash it's by default 720p.
It would be great to have more options in preferencies for dash like:
- 144p dash
- 240p dash
- 320p dash
- 480p dash
- 720p dash
- 1080p dash

**Comment by unixfox** [comment] 2019-11-28 21:11
Probably duplicate of https://github.com/omarroth/invidious/issues/646

**Comment by omarroth** [comment] 2020-01-22 02:30
Closing in favor of #646.

**Closed by omarroth** 2020-01-22 02:30 UTC
Labels: question
