### ISSUE TITLE
problems with playlists imported from newpipe.

### ISSUE THREAD

**Issue by GitJamz** [omarroth/invidious#991] opened 2020-01-17 17:45 UTC
Hi,
I have just created a account on a invidious instance - snopyta.
Then imported data.zip from my newpipe containing playlists and subscribtions.
I import it in invidious and the subscribtions works but not the playlists. It just gives me:
Looks like you've found a bug in Invidious. Feel free to open a new issue here or send an email to support@snopyta.org

Thanks

**Comment by Perflyst** [comment] 2020-01-17 18:29
The only error I can see around this timestamp is (but I do get this exact error very often so unlikely this was due to your import)
```
Jan 17 19:46:10 invidious invidious[15025]: Unhandled exception on HTTP::Handler
Jan 17 19:46:10 invidious invidious[15025]: Missing hash key: "preferences" (KeyError)
Jan 17 19:46:10 invidious invidious[15025]:   from /usr/share/crystal/src/hash.cr:1027:11 in '[]'
Jan 17 19:46:10 invidious invidious[15025]:   from lib/kemal/src/kemal/ext/context.cr:50:7 in 'get'
Jan 17 19:46:10 invidious invidious[15025]:   from src/invidious.cr:2:17 in '->'
Jan 17 19:46:10 invidious invidious[15025]:   from lib/kemal/src/kemal/config.cr:255:3 in '->'
Jan 17 19:46:10 invidious invidious[15025]:   from src/invidious/helpers/handlers.cr:255:3 in 'call_exception_with_status_code'
Jan 17 19:46:10 invidious invidious[15025]:   from lib/kemal/src/kemal/exception_handler.cr:15:14 in 'call'
Jan 17 19:46:10 invidious invidious[15025]:   from /usr/share/crystal/src/http/server/handler.cr:26:7 in 'call_next'
Jan 17 19:46:10 invidious invidious[15025]:   from src/invidious/helpers/logger.cr:16:5 in 'call'
Jan 17 19:46:10 invidious invidious[15025]:   from /usr/share/crystal/src/http/server/handler.cr:26:7 in 'call_next'
Jan 17 19:46:10 invidious invidious[15025]:   from lib/kemal/src/kemal/init_handler.cr:12:7 in 'call'
Jan 17 19:46:10 invidious invidious[15025]:   from /usr/share/crystal/src/http/server/request_processor.cr:48:11 in 'process'
Jan 17 19:46:10 invidious invidious[15025]:   from /usr/share/crystal/src/http/server/request_processor.cr:22:3 in 'process'
Jan 17 19:46:10 invidious invidious[15025]:   from /usr/share/crystal/src/http/server.cr:497:5 in 'handle_client'
Jan 17 19:46:10 invidious invidious[15025]:   from /usr/share/crystal/src/http/server.cr:463:13 in '->'
Jan 17 19:46:10 invidious invidious[15025]:   from /usr/share/crystal/src/fiber.cr:255:3 in 'run'
Jan 17 19:46:10 invidious invidious[15025]:   from /usr/share/crystal/src/fiber.cr:47:34 in '->'
Jan 17 19:46:10 invidious invidious[15025]:   from ???
```

How big is the zip file you upload? Can you maybe try it on https://invidio.us too?

**Comment by omarroth** [comment] 2020-02-01 16:26
Duplicate of #985. Currently playlists cannot be imported or exported.

**Closed by omarroth** 2020-02-01 16:26 UTC
Labels: duplicate, enhancement
