### ISSUE TITLE
[Feature Request] Sort search results options

### ISSUE THREAD

**Issue by rex4539** [omarroth/invidious#1006] opened 2020-01-28 13:06 UTC
Similar to YouTube.

<img width="855" alt="Screen Shot 2020-01-28 at 15 05 38" src="https://user-images.githubusercontent.com/227442/73266510-adf13500-41df-11ea-93ee-8acfca8d3632.png">

**Comment by omarroth** [comment] 2020-02-01 16:20
Duplicate of #179.

**Closed by omarroth** 2020-02-01 16:20 UTC
Labels: duplicate, enhancement
