### ISSUE TITLE
Issue with viewing a video in Internet Explorer

### ISSUE THREAD

**Issue by Zero3K** [omarroth/invidious#105] opened 2018-08-10 21:36 UTC
The player size is too small when viewing a video in Internet Explorer 11.

**Comment by omarroth** [comment] 2018-08-11 16:00
I unfortunately can't test this myself, could you provide a screenshot of what you're seeing?

**Comment by omarroth** [comment] 2018-08-25 21:54
I found a way to test this, and it appears to be working as expected:
![image](https://user-images.githubusercontent.com/14208607/44622880-5ed70000-a887-11e8-85b5-fda38207342f.png)

It may have been fixed by another change, but I would see if it still occurs. A script may have failed to load or some other issue that I am having trouble reproducing.

**Comment by Zero3K** [comment] 2018-08-25 22:55
That's not based on Internet Explorer 11.

**Comment by omarroth** [comment] 2018-08-25 23:15
That's my bad. Is there any way for you to open a console to see if it's throwing any error messages?

**Comment by Zero3K** [comment] 2018-08-26 00:01
Nope. We need someone who still has Internet Explorer 11 in order for the issue to be figured out and fixed.

**Comment by Avizini** [comment] 2018-08-27 14:57
Is this what you need?

![Wait for this image to load..](https://user-images.githubusercontent.com/37608661/44667148-83f37c00-aa09-11e8-97db-fc34d5df5cf5.png)

Test it with IE11 on Win7 yourself, [Browserling - IE11, Win7 | Invidio.us](https://www.browserling.com/browse/win/7/ie/11/https%3A%2F%2Fwww.invidio.us%2Fwatch%3Fv%3DlRfdMiURV4sl)

**Comment by Zero3K** [comment] 2018-08-27 18:45
Also, All versions of Chrome up to v41 have the same issue as IE 11.

**Comment by omarroth** [comment] 2018-09-13 23:19
Appears to be fixed with 2232bc0. More details in the commit, but essentially older browsers don't support \`multiline string\` syntax. It works for me in Chrome v40 and IE 11, but I'd like some other folks to confirm before this issue is closed.

**Comment by Zero3K** [comment] 2018-09-14 00:17
It works now in IE 11.

**Comment by omarroth** [comment] 2018-09-14 21:03
:+1:

**Closed by omarroth** 2018-09-14 21:03 UTC
