### ISSUE TITLE
Cutoffs, endless buffering, false endings, breakage

### ISSUE THREAD

**Issue by Tharn** [omarroth/invidious#649] opened 2019-07-30 14:52 UTC
I don't know why this is (assume it has to do with DASH), but right now Invidious is unusable for regular watching. Doesn't matter if the video is long or short, most of the time it stops playing at some point. The controls may become unresponsive, or the counter may keep ticking. Reloading the page (unfortunately) retains the old cache and other issues so you get the same stalling behaviour or playing a black screen while the progress bar thumbnail shows actual content. The video may 'break' where it keeps playing with a black screen and audio distortions and pops.

Even videos that play well almost to the end often do a 'false ending' somewhere in the last quarter where buffer runs empty and the last bit won't be loaded.

**Comment by omarroth** [comment] 2019-07-30 15:15
Appears to be duplicate of #616. Does this only occur on https://invidio.us, or are you able to reproduce with [another instance](https://github.com/omarroth/invidious/wiki/Invidious-Instances)?

**Comment by Tharn** [comment] 2019-07-30 16:18
I tried it with invidious.snopyta.org and am *pretty sure* it happened then also. But will check some other instances.

**Comment by Tharn** [comment] 2019-08-03 14:50
Yea, seems related to website load.

**Comment by omarroth** [comment] 2019-08-15 14:13
Closing in favor of #616.

**Closed by omarroth** 2019-08-15 14:13 UTC
Labels: bug
