### ISSUE TITLE
Here's a script that I use for redirecting Youtube to Invidious

### ISSUE THREAD

**Issue by Zero3K** [omarroth/invidious#65] opened 2018-08-02 23:54 UTC
*subject*

[Youtube_to_Invidious.txt](https://github.com/omarroth/invidious/files/2255513/Youtube_to_Invidious.txt)

Rename it from .txt to .user.js.

**Comment by veloute** [comment] 2018-08-03 00:26
https://github.com/omarroth/invidious/pull/66

**Comment by Zero3K** [comment] 2018-08-03 00:32
Its different than the one on Greasyfork.

**Comment by veloute** [comment] 2018-08-03 00:35
Does your one have any improvements to the other?

**Comment by Zero3K** [comment] 2018-08-03 02:14
It doesn't send requests to Youtube when redirecting embedded videos to Invidious.

**Comment by Zero3K** [comment] 2018-08-03 02:46
Its not mine.

**Comment by omarroth** [comment] 2018-08-03 03:44
Looks like a duplicate of the script in #66, so I'm going to close this. If there's a project page for this script anywhere then feel free to open a PR.

**Closed by omarroth** 2018-08-03 03:44 UTC

**Comment by Zero3K** [comment] 2018-08-03 13:48
Its not a complete duplicate.
