### ISSUE TITLE
Add system requirements for installation

### ISSUE THREAD

**Issue by aabbcdd99** [omarroth/invidious#1258] opened 2020-06-19 00:37 UTC
Installation fails (both master & release) with 2 GB  of RAM.
```
...
Using protodec (0.1.3)
Using lsquic (0.1.9 at 5261034)
$ crystal build src/invidious.cr --release
LLVM ERROR: out of memory
Aborted
```

Please add system requirements for the invidious setup.

**Comment by SuperSandro2000** [comment] 2020-06-19 17:18
Duplicate of #1152

**Closed** 2020-06-23 15:14 UTC
