### ISSUE TITLE
60 fps videos support

### ISSUE THREAD

**Issue by dimqua** [omarroth/invidious#189] opened 2018-09-27 20:36 UTC
Is it possible to add a support of 60 fps videos to Invidious?

**Comment by omarroth** [comment] 2018-09-27 20:45
Yep. Since only 1080p streams can be 60fps, I would consider this a duplicate of #34.

**Comment by Discookie** [comment] 2018-09-27 20:49
Technically 720p can be 60fps too, but it involves the same technology that regular 1080p streams use.

**Comment by dimqua** [comment] 2018-09-27 20:55
@omarroth this video has 720p60 quality, according to youtube-dl:
https://www.youtube.com/watch?v=lTiBhGCbwps

**Comment by omarroth** [comment] 2018-09-27 21:03
Yeah, I misspoke. 720p or higher can be 60fps, not 1080p. But like @Discookie said, 60fps is reserved for DASH streams only. Running `ffprobe` on an `hd720` file reveals:
```
    Stream #0:0(und): Video: h264 (Main) (avc1 / 0x31637661), yuv420p(tv, bt709), 1280x720 [SAR 1:1 DAR 16:9], 1095 kb/s, 29.97 fps, 29.97 tbr, 90k tbn, 59.94 tbc (default)
```
So I think 60fps comes along with adding support for 1080p.

**Closed** 2018-09-27 22:09 UTC
