### ISSUE TITLE
Whitespaces in thumbnails

### ISSUE THREAD

**Issue by dimqua** [omarroth/invidious#171] opened 2018-09-17 13:01 UTC
There are an unneeded whitespaces in invidious thumbnails.

* original: https://i.ytimg.com/vi/YE7VzlLtp-4/maxresdefault.jpg
* https://www.invidio.us/vi/YE7VzlLtp-4/maxresdefault.jpg
* https://www.invidio.us/vi/YE7VzlLtp-4/maxres.jpg

BTW, what's the difference between the two (`maxresdefault.jpg` and `maxres.jpg`)?

**Comment by omarroth** [comment] 2018-09-17 14:46
`maxres.jpg` will automatically pick the highest resolution thumbnail available for a video, as videos below 720p don't have `maxresdefault.jpg` and other videos do not have consistent sizes available (besides low-quality `default.jpg`, etc.).

I can replicate the issue, but it seems very strange to me. Downloading the image (for example with `wget https://www.invidio.us/vi/YE7VzlLtp-4/maxresdefault.jpg`) will produce the expected result, but browsers add whitespace. In addition, it only happens on some thumbnails, for example:
- https://i.ytimg.com/vi/Ud3N7BFsDG0/maxresdefault.jpg
- https://invidio.us/vi/Ud3N7BFsDG0/maxresdefault.jpg

Does not have whitespace.

**Comment by Discookie** [comment] 2018-09-17 15:45
If you open the YouTube image and the Invid image in an editor, you can see that the last few bytes are cut off. The rest of the file is the same.
This is further confirmed by the size being smaller for the image served by Invid.

Looks like the proxy cuts off the end of some images, It doesn't do it for all of them though, which is weird.

Firefox throws an "Image corrupted or truncated" error too.

**Comment by omarroth** [comment] 2018-09-17 15:59
Thanks. My guess is that the proxy isn't properly closing the connection with the browser, which seems quite strange. For reference, the code for proxying images is [here](https://github.com/omarroth/invidious/blob/master/src/invidious.cr#L2989-L3046).

**Comment by omarroth** [comment] 2018-09-17 19:51
Appears to be fixed with 83ba4e2a4c1cb974d20499867b0fd445071ea07e.

**Closed** 2018-09-20 09:26 UTC
