### ISSUE TITLE
invidio.us returns no search results

### ISSUE THREAD

**Issue by anonym2048** [omarroth/invidious#1243] opened 2020-06-15 18:12 UTC
Hi, when I try to search something on the official instance it doesn't return anything. It worked a few hours ago, so I'm just wondering what's going on. 

Try for example this:
https://invidio.us/search?q=test

**Comment by Perflyst** [comment] 2020-06-15 18:13
Duplicate of #1241

**Closed by Perflyst** 2020-06-15 18:13 UTC
