### ISSUE TITLE
Wrong view count on the home page

### ISSUE THREAD

**Issue by B0pol** [omarroth/invidious#1240] opened 2020-06-15 15:55 UTC
from invidio.us popular page:

![image](https://user-images.githubusercontent.com/58657617/84679051-16437780-af31-11ea-9aa1-6c6ab82fbca1.png)
You can notice the three most viewed videos have extremely view count

![image](https://user-images.githubusercontent.com/58657617/84679148-37a46380-af31-11ea-995b-83c57ff4b671.png)
It does not happen on the channel page

![image](https://user-images.githubusercontent.com/58657617/84679221-4f7be780-af31-11ea-8ae8-cfc618a31633.png)
neither on the video page

**Comment by TheFrenchGhosty** [comment] 2020-06-15 18:45
Duplicate of https://github.com/omarroth/invidious/issues/890

**Closed** 2020-06-15 19:58 UTC
Labels: duplicate
