### ISSUE TITLE
Apparently I've found a big in invidious...

### ISSUE THREAD

**Issue by SuperRobinHood** [omarroth/invidious#795] opened 2019-10-03 17:06 UTC
While trying to watch this video: https://invidio.us/watch?v=h9girlHaXgU the message "Looks like you've found a bug in Invidious. Feel free to open a new issue here or send an email to omarroth@protonmail.com. " appears. So, I'm posting this here as instructed. Browser is Pale Moon if that matters.

**Comment by xiriloj-installlinux** [comment] 2019-10-03 19:10
@SuperRobinHood  works for me on Brave
Version 0.72.64 Chromium: 77.0.3865.90 (Official Build) nightly (64-bit)

First there was the message, that the "The media could not be loaded, either because the server or network failed or because the format is not supported."

But after some seconds it worked.

**Comment by yustAnotherUser** [comment] 2019-10-04 01:32
Hello, everybody,

I have now specifically registered for this comment.
It looks like a session or timing problem (just guessed).
It just happened to me for the first time in a browser tab that was open for many hours but the video couldn't be loaded first. I don't know 100% where I clicked but I think on Play and afterwards ended up on the "looks like you found a bug page".

I hope that this can be useful, it's not really a problem. A simple F5 is enough to solve the problem.
 
Many thanks for this project!

**Comment by yustAnotherUser** [comment] 2019-10-04 18:45
ok guys... found another video...
this link gets you to the error page immediately and every time - no problems on this channel before right now..
https://invidio.us/watch?v=nheTjjQzqcs

**Comment by SmallJoker** [comment] 2019-10-04 18:45
The original posted video works fine for me, but even with Ctrl+F5 (force reload, clear cache) for https://invidio.us/watch?v=oYAiElvS0-A does not make the error message disappear.

Settings: Audio playback by default
Country: CH (If this matters)

**Comment by yustAnotherUser** [comment] 2019-10-04 18:47
> The original posted video works fine for me, but even with Ctrl+F5 (force reload, clear cache) for https://invidio.us/watch?v=oYAiElvS0-A does not make the error message disappear.
> 
> Settings: Audio playback by default
> Country: CH (If this matters)

confirmed!

**Comment by weisenhan** [comment] 2019-10-04 21:05
@omarroth

It looks like I found another one. https://www.invidio.us/watch?v=mmyjBIo5ncE
The video also will not play from the embedded youtube page. https://www.youtube.com/embed/mmyjBIo5ncE still plays on the original youtube page https://www.youtube.com/watch?v=mmyjBIo5ncE

**Comment by omarroth** [comment] 2019-10-04 21:43
The description appears to be missing in some cases, which causes Invidious to fail.

Should be (partially) fixed with 2d59fdd178c211cc365976f736ce42fa124d5968. I'd like to look into this a bit more before closing.

**Comment by omarroth** [comment] 2019-10-09 14:08
This is caused by rate-limiting by Google. Closing in favor of #811.

**Closed by omarroth** 2019-10-09 14:08 UTC
Labels: bug
