### ISSUE TITLE
[Feature Request] Having the channel statistics on the channel page

### ISSUE THREAD

**Issue by TheFrenchGhosty** [omarroth/invidious#710] opened 2019-08-19 04:24 UTC
Right now the only way to see the exact number of subscribers and the total number of videos of a channel is to search for it, and there is no way to see the total channel views and the join date of the creator (YouTube provide these datas on the "About" tab)

It might be a good idea to have it under the channel description like this (maybe with a different order): 

![invidious](https://user-images.githubusercontent.com/47571719/63239100-21f2de80-c239-11e9-9214-22753ff55023.png)

See also: #483.

**Comment by omarroth** [comment] 2019-08-20 04:02
Rather than having two subscriber counts I think it makes sense to only have the subscribe widget with an accurate subscriber count. Otherwise appears to be a duplicate of #483.

**Comment by omarroth** [comment] 2019-08-21 23:04
Closing in favor of #483.

**Closed by omarroth** 2019-08-21 23:04 UTC
Labels: enhancement
