### ISSUE TITLE
Add "Autoplay" button for playlists embeds

### ISSUE THREAD

**Issue by Booteille** [omarroth/invidious#492] opened 2019-04-14 23:57 UTC
Hi!

I think there should be an option to autoplay (not just load it) videos from a playlist once the user enabled it.

**Comment by omarroth** [comment] 2019-04-15 00:52
Duplicate of #268?

**Comment by Booteille** [comment] 2019-04-16 16:28
Sorry, I didn't well explained what I had in mind.

I was thinking about a specific button, incorporated on the embed player. 

But after I've read your last comment on this issue, I think it can be considered as a duplicate, yeah.

**Closed** 2019-04-17 12:57 UTC
Labels: duplicate
