### ISSUE TITLE
Videos Not Appear In Subscriptions Feed Page

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [omarroth/invidious#329] opened 2019-01-31 19:45 UTC
It's happening from somedays, videos not appear in subscriptions feed page like here pewdiepie videos uploaded from 23 hours & 1 hour & it didn't appear in subscriptions feed page 
![2019-01-31_214022](https://user-images.githubusercontent.com/28893833/52080865-7f775480-25a1-11e9-89d3-0035e65d0784.png)
![2019-01-31_214032](https://user-images.githubusercontent.com/28893833/52080932-a0d84080-25a1-11e9-86ec-b85e0b1e51dc.png)
![2019-01-31_214041](https://user-images.githubusercontent.com/28893833/52080867-7f775480-25a1-11e9-97ab-3c505f154d8a.png)

**Comment by omarroth** [comment] 2019-01-31 19:57
Duplicate of #326. I'm looking into it right now.

**Closed** 2019-02-01 02:15 UTC
