### ISSUE TITLE
No compatible source was found for this media.

### ISSUE THREAD

**Issue by xtianmind** [omarroth/invidious#263] opened 2018-12-09 16:59 UTC
Everytime I am logged in to Invidious (not through Google) and I try to watch a video I get this message on the video "No compatible source was found for this media."

This only happens when I am logged in. I tried to change settings to see if it would fix it. But could not fix it. Any solutions?

**Comment by omarroth** [comment] 2018-12-12 17:47
It's strange that it should only happen when you're logged in, you might check devtools to see if it's showing any errors. Does it happen on every video you try or just specific ones?

**Comment by xtianmind** [comment] 2018-12-12 20:41
I actually fixed the problem. I had changed the settings to Preferred Video Quality and selected small. I guess that one doesn't work on my computer. I changed it back to hd720 and it's working again.

Thank you for your help. I love the site. I use it daily.

**Comment by xtianmind** [comment] 2018-12-12 20:45
In case you're curious the error code I got in Dev Tools:

video.min.js:1 VIDEOJS: WARN: videojs.plugin() is deprecated; use videojs.registerPlugin() instead
Ze @ video.min.js:1

video.min.js:1 VIDEOJS: ERROR: (CODE:4 MEDIA_ERR_SRC_NOT_SUPPORTED) No compatible source was found for this media. st

**Comment by omarroth** [comment] 2018-12-15 17:42
Thanks. I think I'll probably close this. The issue is with better error-handling for the player, which should be fixed with #236.

**Closed by omarroth** 2018-12-15 17:42 UTC
