### ISSUE TITLE
feature request: sort videos by upload date / relevancy/ rating

### ISSUE THREAD

**Issue by lairichard** [omarroth/invidious#1144] opened 2020-04-27 22:26 UTC
U know that tab u can click that lets u search for channels, upload date etc. on youtube.. If there were some way to replicate that on here it would be nice.

**Comment by pluja** [comment] 2020-05-07 07:01
This would be really nice!

**Comment by Perflyst** [comment] 2020-05-26 18:11
Duplicate of #179

**Closed by Perflyst** 2020-05-26 18:11 UTC
