### ISSUE TITLE
504 Gateway Time-out, The server didn't respond in time. 

### ISSUE THREAD

**Issue by ChloeMackey** [omarroth/invidious#173] opened 2018-09-18 18:01 UTC
Anyone else getting that message when trying to access their subscriptions?

**Comment by Zero3K** [comment] 2018-09-18 18:07
I can confirm that it is happening for me. I thought it was fixed.

**Comment by omarroth** [comment] 2018-09-18 20:00
It's a problem that occurs when the load reaches a certain threshold. So it's not so much permanently fixed as the server is upgraded to handle the increased usage.

**Comment by EsmailELBoBDev2** [comment] 2018-09-18 20:13
@omarroth i getting same error when i try open https://invidio.us/feed/subscriptions

**Comment by dimqua** [comment] 2018-09-18 20:34
Me too.

**Comment by Discookie** [comment] 2018-09-19 14:40
I think it's also an issue that the site doesn't have proper error pages:
  - for 503/504 one that would explain that the servers are overloaded
  - for 500 one that would point them to make an issue here
  - etc etc.

I know some errors (like 404) do have their own pages, but I think all but the worst errors should be caught before the user sees them.

**Comment by d3d1rty** [comment] 2018-09-19 20:17
> It's a problem that occurs when the load reaches a certain threshold. So it's not so much permanently fixed as the server is upgraded to handle the increased usage.

Any idea of what the associated costs would be with upgrading the server to handle it?

**Comment by omarroth** [comment] 2018-09-19 20:22
Right now I'm looking into optimizing rather than upgrading, but if/when I were to upgrade, it would probably be about a ~$20 increase.

**Comment by omarroth** [comment] 2018-09-20 14:28
I just upgraded the server, and now am able to access my feed. If others find the same, then we can probably close this for now. I'm still looking into optimizing it as much as I can, but in the short-term this appears to be fixed.

**Comment by omarroth** [comment] 2018-09-20 23:54
Thanks. For folks that would like to see how Invidious queries the DB, I'd take a look [here](https://github.com/omarroth/invidious/blob/master/src/invidious.cr#L1338-L1363), and the table schema is [here](https://github.com/omarroth/invidious/blob/master/config/sql/channel_videos.sql). I'd be very interested and thankful for thoughts as to how it could be improved.

**Comment by Discookie** [comment] 2018-09-21 08:44
I don't see why the index `channel_videos_ucid_idx` is using btree instead of hash. It would gain quite a bit of performance, and I don't think you use < or > comparisons on it.

Another marginal gain in query speed would be to store all video ID's as 64-bit integers.

The id stores a variant of b64 characters - together these characters add up to 66 bits. But YouTube just doesn't care about the last 2 bits, so all of these open the same video:
https://www.youtube.com/watch?v=dvz9lsaIKLY
https://www.youtube.com/watch?v=dvz9lsaIKLZ
https://www.youtube.com/watch?v=dvz9lsaIKLa
https://www.youtube.com/watch?v=dvz9lsaIKLb

Channel IDs could be similarly shortened, although they are 132 bits long, and I don't know whether they ignore any bits or not.

**Comment by omarroth** [comment] 2018-09-21 13:34
Thank you! That definitely helps a lot. 

The comment about video IDs is interesting, but unfortunately the examples provided (except the first) return a `Does not exist`. My understanding is that YouTube uses some variant of [hashids](https://hashids.org/) internally.

**Comment by Discookie** [comment] 2018-09-21 13:46
Yeah, if you query them, they don't return anything, but if you open them on Youtube, they redirect to the first link. (This seems like a separate issue?)
A common example is linking the Rickroll video with the ending of XcR, XcS, etc. to trick you into clicking on an unvisited link :P

**Comment by omarroth** [comment] 2018-09-22 14:30
Opening the links on YouTube results in a `Does not exist` as well. If a videoID is longer than 11 characters then YouTube will strip the extraneous ones, and Invidious does that as well. For example:
- https://www.youtube.com/watch?v=dvz9lsaIKLY
- https://www.youtube.com/watch?v=dvz9lsaIKLYXcR

Unfortunately, I'm still encountering this issue, if there's any other suggestions I would be very eager to hear them.

**Comment by omarroth** [comment] 2018-10-09 13:54
I'm pushing out 35e63fa3f5472f847044499ce6d2c6a44220ce07 right now which should speed up subscriptions significantly, and we can hopefully close this. There's some more info on how it works in yesterday's [release](https://github.com/omarroth/invidious/releases/tag/0.9.0).

I expect the migration to take ~1.5 hours. Everything except subscriptions should still be available during this time. Thanks everyone.

**Comment by d3d1rty** [comment] 2018-10-09 16:01
Just checked and the issue seems to be corrected. Much faster response. I had previously adjusted my settings to only show unseen notifications, so I reset it so that it shows everything with 25 results in the feed. First attempt was successful, super fast response, so I adjusted the results to 50 and then 100 videos in the feed. I ran 3 attempts per setting (25, 50, and 100) and recorded the results below.

Response Times:
* 25 videos: 70 ms, 119 ms, 96 ms
* 50 videos: 76 ms, 166 ms, 385 ms
* 100 videos: 225 ms, 133 ms, 143 ms

**Comment by omarroth** [comment] 2018-11-02 13:31
I'd be very interested to investigate, would you mind opening a new issue?

**Comment by dotdapple** [comment] 2018-11-02 13:36
#215

**Comment by omarroth** [comment] 2018-11-07 04:54
It seems no one has encountered this for about a month, so I think I'll close this. If anyone encounters this again feel free to open a new issue, or I'll be happy to reopen.

**Closed by omarroth** 2018-11-07 04:54 UTC
Labels: bug

**Comment by jeroen7s** [comment] 2018-12-12 14:12
now i'm encountering it :(
