### ISSUE TITLE
project documentation/webpage lack clear info about wtf is this

### ISSUE THREAD

**Issue by icf20** [omarroth/invidious#969] opened 2019-12-30 01:33 UTC
> Invidious is an alternative front-end to YouTube

by general average education should i know what "front-end to YouTube" or do i need to google/youtube this?

on https://invidio.us/

i was looking at the bottom there is no about us or anything to explain what is this project or what is doing

**Comment by TheFoxStudio** [comment] 2020-01-19 23:46
Personally I think if you do not know what a front-end is, you should probably not consider tinkering with software like this.
People that will be able to work with this and have a basic technology understanding will understand what it stands for.

**Comment by omarroth** [comment] 2020-01-20 21:27
Duplicate of #767.

I agree that there could be better communication about what the project is. I would recommend taking a look at #744 to see if that addresses your needs.

**Closed by omarroth** 2020-01-20 21:27 UTC
