### ISSUE TITLE
Slow buffering of videos, what makes them frequently stop..

### ISSUE THREAD

**Issue by Kiude** [omarroth/invidious#676] opened 2019-08-07 10:28 UTC
Hi, I just discovered Invidious this week, using it coupled with Invidition addon.

I love the project and want to keep using it. However in a lot of videos (I might say all of them..) the video frequently stops for buffering reasons. I switched to medium resolution and it doesnt help, while I can easily watch 1080p vids on Youtube..

Does anyone know what might cause this trouble? Im browsing with latest Firefox version.

Thank you for any help,

**Comment by omarroth** [comment] 2019-08-09 02:31
Likely duplicate of #649, #616, #562. Does this only occur when using dash? Is this an issue only with https://invidio.us, or can you reproduce this on [another instance](https://github.com/omarroth/invidious/wiki/Invidious-Instances)?

**Comment by Kiude** [comment] 2019-08-17 14:11
Hey! Sorry to get back at you so late, I wanted to use the trick for a while to be sure the problem had been solved.

It appears switching to snopyta.org did the trick. I no longer experience these chronic buffering freezes. Thank you for your help and sorry for not having duplicated an issue thread.

**Comment by omarroth** [comment] 2019-08-21 23:31
Absolutely no worries. Closing in favor of #616.

**Closed by omarroth** 2019-08-21 23:31 UTC
Labels: bug
