### ISSUE TITLE
Error on build using Docker Deploy

### ISSUE THREAD

**Issue by m4teh** [omarroth/invidious#888] opened 2019-11-08 11:22 UTC
- Using Invidious Updater 1.4.0
- Deploy with Docker
- Fresh build with no existing docker images/folder data
- Tried master & release

> Step 7/20 : COPY ./.git/ ./.git/
 ---> Using cache
 ---> cdb363d540fc
Step 8/20 : RUN crystal build --static --release --warnings all --error-on-warnings     -Dmusl     ./src/invidious.cr
 ---> Running in 9fc75caf780e
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libxml2.a(xzlib.o): in function `xz_decomp':
/home/buildozer/aports/main/libxml2/src/libxml2-2.9.9/xzlib.c:581: undefined reference to `lzma_code'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libxml2.a(xzlib.o): in function `xz_head':
/home/buildozer/aports/main/libxml2/src/libxml2-2.9.9/xzlib.c:411: undefined reference to `lzma_auto_decoder'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libxml2.a(xzlib.o): in function `is_format_lzma':
/home/buildozer/aports/main/libxml2/src/libxml2-2.9.9/xzlib.c:312: undefined reference to `lzma_properties_decode'
/usr/lib/gcc/x86_64-alpine-linux-musl/9.2.0/../../../../x86_64-alpine-linux-musl/bin/ld: /usr/lib/libxml2.a(xzlib.o): in function `__libxml2_xzclose':
/home/buildozer/aports/main/libxml2/src/libxml2-2.9.9/xzlib.c:799: undefined reference to `lzma_end'
collect2: error: ld returned 1 exit status
Error: execution of command failed with code: 1: `cc "${@}" -o '/invidious/invidious'  -rdynamic -static  /usr/lib/libyaml.a /usr/lib/libxml2.a /usr/lib/libsqlite3.a -lz `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libssl || printf %s '-lssl -lcrypto'` `command -v pkg-config > /dev/null && pkg-config --libs --silence-errors libcrypto || printf %s '-lcrypto'` /usr/lib/libpcre.a /usr/lib/libm.a /usr/lib/libgc.a /usr/lib/libpthread.a /usr/lib/crystal/core/ext/libcrystal.a /usr/lib/libevent.a /usr/lib/librt.a -L/usr/lib -L/usr/local/lib`
ERROR: Service 'invidious' failed to build: The command '/bin/sh -c crystal build --static --release --warnings all --error-on-warnings     -Dmusl     ./src/invidious.cr' returned a non-zero code: 1
✔ Deployment done.
➜ Checking for updates...
✔ No update available.

Full log: https://pastebin.com/qc7iiPHj

**Comment by omarroth** [comment] 2019-11-08 13:45
Duplicate of #872. Currently several dependencies are flagged as out of date (in this case appears to be [libxml2](https://pkgs.alpinelinux.org/package/edge/main/x86_64/libxml2)).

**Closed by omarroth** 2019-11-08 13:45 UTC
Labels: bug, duplicate
