### ISSUE TITLE
Hello why not work get video page data ?

### ISSUE THREAD

**Issue by yaskammm** [omarroth/invidious#840] opened 2019-10-20 11:23 UTC
Hello why not work get video page data ? I get this errro Video unavailable.
https://mp3lerindir.biz/watch?v=cgeUysHOLKQ
How fix this ? I Thnik this google want captcha issuse 
https://ru-clip.net/video/c3prYnNzy3M/sen-anlat-karadeniz-60-b%C3%B6l%C3%BCm.html and a lot of  other site fix this problem.How fix this problem ? Please help me

**Comment by omarroth** [comment] 2019-10-20 16:38
Duplicate of #811. If you have IPv6 available for your machine you may try setting `force_resolve: ipv4` or `force_resolve: ipv6`.

**Closed by omarroth** 2019-10-20 16:38 UTC
Labels: duplicate, question

**Comment by yaskammm** [comment] 2019-10-20 20:58
How using force_resolve: ipv6 ? Please help me

**Comment by omarroth** [comment] 2019-10-22 22:20
In your configuration file `config/config.yml`. Like so:

```yaml
channel_threads: 1
feed_threads: 1
db:
  user: kemal
  password: xxxx
  host: 127.0.0.1
  dbname: invidious

# ...

force_resolve: ipv6 # <---
```
