### ISSUE TITLE
Rebulding does not working

### ISSUE THREAD

**Issue by haizrul** [omarroth/invidious#947] opened 2019-12-04 08:50 UTC
I changed something in config file and save. I rebuild using these 3 commands :

cd /home/invidious/invidious
crystal build src/invidious.cr --release
sudo systemctl restart invidious.service

But nothings changed. I don't know why. Please help.

**Comment by tleydxdy** [comment] 2019-12-04 16:02
what's the error? 😑

**Comment by Perflyst** [comment] 2019-12-05 17:04
Likely duplicate of #917

**Comment by gled-rs** [comment] 2019-12-05 19:18
probably the same as https://github.com/omarroth/invidious/issues/917#issuecomment-562273603

**Comment by omarroth** [comment] 2019-12-05 20:32
Closing in favor of #917. Try building without `--release`.

**Closed by omarroth** 2019-12-05 20:32 UTC
