### ISSUE TITLE
Won't let me log in

### ISSUE THREAD

**Issue by jaruiz59** [omarroth/invidious#1002] opened 2020-01-25 22:20 UTC
Everytime I try to log in I always get a weird message about Expected array.
![Screenshot 2020-01-25 at 5 15 25 PM](https://user-images.githubusercontent.com/47218326/73128017-fbc72c80-3f96-11ea-8ab4-d72724ac1af0.png)

**Comment by unixfox** [comment] 2020-01-27 10:48
Duplicate of #755

**Closed** 2020-02-01 01:02 UTC
Labels: bug, duplicate

**Comment by GMartigny** [comment] 2020-03-25 10:00
Hi @omarroth,

This didn't feel like a duplicate of #755.
I have the same issue as OP, the page don't say the account is disabled or anything. It looks like an internal server error during the login phase.

Shown error:
```
Expected Array for #[]?(index : Int), not Int64
Traceback:
	Getting lookup...done, returned 200.
	Getting challenge...done, returned 400.
```
