### ISSUE TITLE
Feed "POPULAR" is empty

### ISSUE THREAD

**Issue by haizrul** [omarroth/invidious#1057] opened 2020-03-08 17:12 UTC
My instance when i clicked on "POPULAR" feed, no videos is showing there. Its empty. Anyone also face the same problem? And how do i fix this? "TOP" & "TRENDING" feeds are working. TQ.

**Comment by omarroth** [comment] 2020-03-10 00:48
Duplicate of #955.

**Closed by omarroth** 2020-03-10 00:48 UTC
Labels: bug, duplicate
