### ISSUE TITLE
add "This video contains content from foo, who has blocked it in your country on copyright grounds." message

### ISSUE THREAD

**Issue by T4eus** [omarroth/invidious#185] opened 2018-09-25 17:56 UTC
Is important do add 
"This video contains content from foo, who has blocked it in your country on copyright grounds."
message for blocked videos, instance of the generic 
"The media could not be loaded, either because the server or network failed or because the format is not supported."

**Comment by omarroth** [comment] 2018-09-26 01:32
Currently, if a video is geo-blocked, it'll show the `This video is not allowed in your country/This video contains content from` message, unless it is able to be proxied by Invidious, in which case it'll show the generic "media could not be loaded", as all the other info on the page is loaded, but the video files are still blocked in the current region. Once the geo-bypass is more consistent I'm planning on proxying the video files as well, so there likely won't be as much of a need for the error message suggested for the player.

**Comment by T4eus** [comment] 2018-09-28 20:40
I understand your point, but I need something to differ errors, like when I get a block from other kind of source error.

**Comment by omarroth** [comment] 2018-09-29 15:34
For videos that Invidious can't get info for, I see this message:
![image](https://user-images.githubusercontent.com/14208607/46247534-66cc1780-c3d2-11e8-917e-da0ada05b263.png)

[This](https://invidio.us/watch?v=sJL6WA-aGkQ) video for example is only whitelisted in Japan. Invidious is able to get info, but the files themselves are not proxied, so they will return 403. Within the week I'm planning on proxying video files as well, so the user will be able to watch all videos Invidious is able to get info for.

For now though, if you are outside the US and in a region where the video is blocked, I would recommend enabling `dash` as your `preferred quality`, since DASH streams are currently the only ones that Invidious proxies, although you will not currently be able to view videos that are blocked in US with DASH. 

This is likely a duplicate of #92.

**Comment by T4eus** [comment] 2018-09-29 15:42
> I would recommend enabling dash as your preferred quality
How I make this?

**Comment by omarroth** [comment] 2018-09-29 15:53
If you go to https://invidio.us/preferences, it should look like this:
![screenshot_20180929_104928](https://user-images.githubusercontent.com/14208607/46247761-afd19b00-c3d5-11e8-8603-2f80cea7d0ae.png)

**Comment by T4eus** [comment] 2018-10-25 13:18
I can't see this page

**Comment by omarroth** [comment] 2018-10-26 03:05
Currently you need to have an account in order to change your preferred quality. If you already have an account, I would be grateful if you could provide more information on the problem.

**Comment by omarroth** [comment] 2019-03-26 22:10
There's now a `&local=true` option that should allow you to view videos that Invidious is able to get info for, which appears to be the problem in this case. You can also set this in your preferences, even if you don't have an account.

Invidious will display the error message if not able to get video links from YouTube, which appears to be the requested functionality, so I'm going to close this.

See also #92.

**Closed by omarroth** 2019-03-26 22:10 UTC
