### ISSUE TITLE
Subtitles don't appear

### ISSUE THREAD

**Issue by jorgesumle** [omarroth/invidious#943] opened 2019-11-30 17:00 UTC
I select subtitles, but they don't appear. I had no problem with subtitles before.

![Screenshot at 2019-11-30 17:59:05](https://user-images.githubusercontent.com/14212780/69903552-d4872100-1392-11ea-8633-1623fd2698f2.png)

**Comment by omarroth** [comment] 2019-12-01 22:53
Duplicate of #916.

**Closed by omarroth** 2019-12-01 22:53 UTC
Labels: bug, duplicate
