### ISSUE TITLE
504 when going on subscription page

### ISSUE THREAD

**Issue by GauthierPLM** [omarroth/invidious#200] opened 2018-10-09 11:38 UTC
Most of the time, i cannot access my subscriptions because I get a 504 Gateway Time-out error (with message `The server didn't respond in time.`).

This happens every days, and almost every time I try to access it. Today, I tried 5 times in 1h and could not reach the subscription page.

**Comment by omarroth** [comment] 2018-10-09 13:54
Duplicate of #173. I'm pushing out 35e63fa3f5472f847044499ce6d2c6a44220ce07 right now which should speed up subscriptions significantly, and we can hopefully close this. There's some more info [here](https://github.com/omarroth/invidious/issues/173#issuecomment-428201000).

**Comment by omarroth** [comment] 2018-10-09 14:58
Closed in favor of #173.

**Closed by omarroth** 2018-10-09 14:58 UTC
