### ISSUE TITLE
Feed doesn't update

### ISSUE THREAD

**Issue by Discookie** [omarroth/invidious#207] opened 2018-10-19 09:37 UTC
I've been checking the feed in the past 2-3 days, but the newest video was never younger than 12 hours.
Several channels uploaded newer videos in that timeframe, but I cannot see them.

Note that this is not a "didn't update since XX:XX", it's consistently behind by the same amount.

**Comment by omarroth** [comment] 2018-10-30 23:46
Are you still encountering this? It appears to update fairly quickly for me.

**Comment by Discookie** [comment] 2018-10-31 01:11
It hasn't been that severe for a while, new videos usually appear between 10 minutes and 2-3 hours after they're made public, if I'm unlucky. But that can be considered normal.

**Comment by omarroth** [comment] 2018-11-07 04:49
I think I'll close this then. Feel free to reopen if it becomes an issue.

**Comment by Discookie** [comment] 2018-11-08 13:31
It's happened again, apparently. Last video is 16 hours ago, right now, with newer ones in a few channels.

(Also I can't reopen it because it was you who closed it :D)

**Comment by omarroth** [comment] 2018-11-08 14:16
Ouch, didn't realize that was the case. I think I know what the issue is, but I'd like for you to close it when it's resolved. Sorry about that.

**Comment by Discookie** [comment] 2018-11-09 20:54
Frozen now for 5-6 hours.

**Comment by Discookie** [comment] 2018-11-26 18:21
Since this has become more of a general "feed's down" issue.

**Closed** 2018-12-14 21:46 UTC
Labels: bug

**Comment by PureTryOut** [comment] 2020-01-12 21:00
Uh, this still happens for me. It has done this for about a month or two, after which it suddenly started working again like 2 weeks ago. But after only a week, it's back to being frozen again.

I'm hosting my own instance, and the older videos that are shown are playing fine. It seems the "trending" page does show recent videos, and even the subscriptions themselves if I navigate to their individual pages., just not my subscriptions feed itself.

**Comment by PureTryOut** [comment] 2020-02-04 09:16
@omarroth could I get some help here? My local instance of invidous is basically useless to me because of this bug.

**Comment by diazepan** [comment] 2020-02-05 01:07
https://github.com/omarroth/invidious/issues/1009
