### ISSUE TITLE
Delay in sub feed page

### ISSUE THREAD

**Issue by EsmailELBoBDev2** [omarroth/invidious#880] opened 2019-11-06 15:03 UTC
well, this bug from a month or even more & it just so annoying i mean i have to wait like more some hours before video show up then after some days when i go down i find new videos released but i did not noticed them because of delay so literally everyday i must check my sub feed for like 3 times to make sure i watched all new videos (the new ones & the new ones whos came with old videos :3 )

**Comment by Perflyst** [comment] 2019-11-06 15:51
Duplicate of #674

**Comment by omarroth** [comment] 2019-11-10 21:45
Closing in favor of #674.

**Closed by omarroth** 2019-11-10 21:45 UTC
Labels: bug, duplicate
