### ISSUE TITLE
Audio stops playing after exiting app or turning screen off for more than 30 seconds on iOS

### ISSUE THREAD

**Issue by SwiftWinds** [omarroth/invidious#1053] opened 2020-03-04 23:19 UTC
I am using Brave Browser on iOS 13.3 of an iPhone 8. Audio stops playing after exiting Brave or turning off the screen for 30 seconds. 

I can continue playing it for about less than a second by pressing the play button in the control center, but then it stops and the control center no longer says anything is playing.

**Comment by SwiftWinds** [comment] 2020-03-05 00:24
UPDATE: this seems to be specific to iOS 13 non-Safari apps (e.g., Brave, Firefox, Chrome), according to this [Apple forums thread](https://discussions.apple.com/thread/250658676?answerId=250658676021#250658676021). Is there some way for Invidious to get around it, or is this an Apple limitation that cannot be bypassed (without something like a jailbreak tweak)?

**Comment by omarroth** [comment] 2020-03-10 15:47
I'm not able to reproduce this on iOS 12.4 (Firefox), so I expect it is specific to iOS 13. Unfortunately I'm not aware of any way this would be bypassed. Generally native apps will have higher privileges, so it's unlikely this could be fixed without jailbreak.

**Closed by omarroth** 2020-03-10 15:47 UTC
Labels: bug
