### ISSUE TITLE
Unexpected Error on login

### ISSUE THREAD

**Issue by bennypr0fane** [omarroth/invidious#1147] opened 2020-04-29 11:46 UTC
I get this error message when trying to login with my Google account:
![Screenshot_20200429_134238](https://user-images.githubusercontent.com/5002396/80592437-bd229180-8a1f-11ea-929e-53605faac9ad.png)
Login is unsuccessful.

**Comment by unixfox** [comment] 2020-05-17 22:41
Probably a duplicate of #755

**Comment by bennypr0fane** [comment] 2020-05-18 11:25
No, it's actually a duplicate of #754

**Comment by unixfox** [comment] 2020-05-18 11:57
OK. Can you then close this issue?

**Closed** 2020-05-18 12:07 UTC
