### ISSUE TITLE
Hide related videos

### ISSUE THREAD

**Issue by tillkrischer** [omarroth/invidious#137] opened 2018-08-30 10:02 UTC
I dislike all the distractions that the standard Youtube interface provides.
So Invidious has been perfect for me.

I think it would be even cleaner in this regard if you could optionally hide the related videos column.

**Comment by dimqua** [comment] 2018-08-30 13:45
See also: #123

**Comment by omarroth** [comment] 2018-08-30 15:11
I'm glad it's been working well for you! Like @dimqua said, I think this is a duplicate of #123.

**Comment by omarroth** [comment] 2018-08-30 21:52
Added with cb01b50.

**Closed by omarroth** 2018-08-30 21:52 UTC
